### ISSUE TITLE
[Feature Request] Auto-Updater

### ISSUE THREAD

**Issue by drewdrew21b** [PSP-Archive/ARK-4#105]
As ARK-4 is released so often (which I think is amazing), it would be nice if there was an autoupdate feature that allowed users to quickly update to the latest build on their wi-fi network without having to connect to a pc, or manually move files around on the device. Depending on how this is implemented, this could be useful for development cycles to immediately test any development builds. Please see below list of suggestions

**Various Suggested Implementations:**
1. If this could support "System Updates" xmb option, or replace "System Updates" with "Custom Firmware Updates" (to make it very obvious this will not update to OFW), utilizing the built-in icon for System update, or some slightly modified icon.
2.  A new application could also be built that performs the updates.
3.  The current ARK Loader application could be enhanced to support updates.
4. Options in Ark Launcher / Recovery  to update. This could be useful if a device is stuck booting into recovery mode due to a broken test build, but an update will fix it.

**Other Considerations:**
- If this could eventually support all PSP Models (1000, 2000, 3000, Go, Vita).
- With how often this is released, consider update thresholds (Nightly, weekly, stable, etc).
- Ensure this supports TimeMacine / Despertar del Cementerio as they rely on some of the same folder structure (Maybe these modules within ARK could just be enhanced to point to the same ARK_01234 path in SaveData which could simplify things, or if supported, a sym link so multiple paths can reference the same folder structure).

**Comment by krazynez** [comment]
So there is one person that does maintain a webpage for ARK to upgrade [here](http://psp.lusidgames.com/). And keeps it upgraded pretty fast, the only really issue with this would be where to host the files? Hosting either cost money or can be a security concern if hosting locally on someones home network. 

I would also like that to be a thing as well just trying to find a way to do this safely and securely with less money overhead is a pain to figure out right now.

**Comment by drewdrew21b** [comment]
I see people on psx-place are using github.io to host simple webpages for various toolsets.

Does it need a full blown Website to host the content, or could the tooling somehow point to the githib release page / content? (Nightly vs Release).

The website you linked to is actually hosted via http:// which isnt necessarily secure (that being said, this is what i have been using myself). 

Not sure if there is limitations with the psp not being updated for several years so, and idk if that means the that it doesnt have a current certificate stack to support github tooling.

**Comment by krazynez** [comment]
The PSP is limited by TLS support only allowing 1.0 and 1.1 (I believe). Modern webpages are 1.2 and even 1.3 now. So Lusid had to kinda shimmy from my understanding to get it to work properly. I believe even though that static page is http the backend running that is actually still modern https with a higher TLS.

**Comment by JoseAaronLopezGarcia** [comment]
We can probably use lucid's site to host the files. From what I can tell by looking at the patches that PRO does, all we need is to host a txt file with the version and have it download a different EBOOT.PBP instead of the official update. This eboot can simlpy be the one that lucid already has, or the ARK Loader.
It can be done, we just need to figure it out.

**Comment by JoseAaronLopezGarcia** [comment]
First part of this feature is ready, the CFW will now attempt to download and run an update:
https://github.com/PSP-Archive/ARK-4/releases/tag/r4208

We don't have an updater ready yet but it will be for the next release. Make sure you install this one so you can use the next update when ready.

**Comment by JoseAaronLopezGarcia** [comment]
Closed as complete.
