### ISSUE TITLE
Built in LED Control

### ISSUE THREAD

**Issue by wally4000** [PSP-Archive/ARK-4#107]
### New Feature

Rather than rely on an external plugin, it would be amazing to have a built in facility that can be controlled via the Custom Firmware Settings to control the LED State for battery performance.

All LEDS should be controllable by the interface( Power, MS Activity, WIFI and Bluetooth on the PSP Go)

This plugin https://www.gamebrew.org/wiki/LED_Control_PSP achieves this by changing the LED state using: sceSysconCtrlLED(SceLED, State)

I would use a plugin but this seems like a good feature to implement into ARK for all :)

**Comment by JoseAaronLopezGarcia** [comment]
Does this plugin work on XMB? I just tried a simple code that works, but not on the XMB, only in games.
I wonder if the XMB uses a different function.
