### ISSUE TITLE
Can't open the Plugins Manager in the XMB

### ISSUE THREAD

**Issue by IceShikurai28** [PSP-Archive/ARK-4#108]
### PSP/Vita Model

PSP-3000 (Slim & Bright)

### ARK Version

4.20.13

### Steps to reproduce

Can't access the Plugins Manager in the XMB.
My PSP freezes then shuts down immediately.

### USB Charge

Disabled

### Overclock

Always

### Power Save

Disabled

### Autoboot Launcher

Disabled

### Disable PSP Go Pause

Disabled

### Unlock Extra Memory

Disabled

### Memory Stick Speedup

Always

### Inferno Cache

Always

**Comment by JoseAaronLopezGarcia** [comment]
what is the contents of plugins.txt if any?

**Comment by IceShikurai28** [comment]
> what is the contents of plugins.txt if any?

None, I figured it only happens when there's no plugin installed at all. I guess I just gotta avoid it now that I don't have any idea which plugins to use or add, lol.

**Comment by krazynez** [comment]
By default we have an "example" plugin to prevent that from happening.

**Comment by JoseAaronLopezGarcia** [comment]
Was this fixed?

**Comment by cyberbasty** [comment]
what's the example plugin ? i have the same problem

**Comment by krazynez** [comment]
> what's the example plugin ? i have the same problem

its just a place holder. You need to have actual plugins in your PLUGINS.TXT to show up.

**Comment by cyberbasty** [comment]
ok thanks

**Comment by cyberbasty** [comment]
i have to put plugins for vsh or for game ?

**Comment by cyberbasty** [comment]
> > i have to put plugins for vsh or for game ?
> 
> Depends on the plugin. Read the instructions of the plugin to know if it's for VSH (XMB), PSP Games or PS1 Games (POPS).

remotejoylite is for all of them

**Comment by JoseAaronLopezGarcia** [comment]
> > > i have to put plugins for vsh or for game ?
> > 
> > 
> > Depends on the plugin. Read the instructions of the plugin to know if it's for VSH (XMB), PSP Games or PS1 Games (POPS).
> 
> remotejoylite is for all of them

then you can use all/always
