### ISSUE TITLE
Load failed. The data is corrupted

### ISSUE THREAD

**Issue by skelletR** [PSP-Archive/ARK-4#111]
### PSP/Vita Model

PSP-N1000 (PSP Go)

### ARK Version

4.20.17

### Homebrew/GAME (if applicable)

Some games with autosave feature

### Steps to reproduce

Open a game and try to load a save

### USB Charge

Always

### Overclock

Disabled

### Power Save

Disabled

### Autoboot Launcher

Disabled

### Disable PSP Go Pause

Disabled

### Unlock Extra Memory

Disabled

### Memory Stick Speedup

Disabled

### Inferno Cache

Disabled

**Comment by skelletR** [comment]
> ### PSP/Vita Model
> PSP-N1000 (PSP Go)
> 
> ### ARK Version
> 4.20.17
> 
> ### Homebrew/GAME (if applicable)
> Some games with autosave feature
> 
> ### Plugins ( if applicable )
> _No response_
> 
> ### Steps to reproduce
> Open a game and try to load a save
> 
> ### USB Charge
> Always
> 
> ### Overclock
> Disabled
> 
> ### Power Save
> Disabled
> 
> ### Autoboot Launcher
> Disabled
> 
> ### Disable PSP Go Pause
> Disabled
> 
> ### Unlock Extra Memory
> Disabled
> 
> ### Memory Stick Speedup
> Disabled
> 
> ### Inferno Cache
> Disabled

Fix it with MagicSave Plugins

**Comment by JoseAaronLopezGarcia** [comment]
This is a regression in 4.20.17 due to the new "old homebrew" patch. I've improved it to get rid of this issue in the latest beta.

**Comment by JoseAaronLopezGarcia** [comment]
This release fixes it: https://github.com/PSP-Archive/ARK-4/releases/tag/r42018

**Comment by skelletR** [comment]
> This release fixes it: https://github.com/PSP-Archive/ARK-4/releases/tag/r42018

Nice. Now i have a problem with infinity boot in the game Jak and Daxter: The Lost Frontier until now, when show the logo sony after show a meteorite fell and black screen and again from the metereon scene infinity
