### ISSUE TITLE
Ability to hide DLC files in the XMB game menu

### ISSUE THREAD

**Issue by DeadLootJ** [PSP-Archive/ARK-4#112]
### New Feature

This is a feature on the PRO/ME firmwares that allowed a user to hide DLC files in the XMB game menu. Is it possible implement this feature into ARK?

**Comment by JoseAaronLopezGarcia** [comment]
The feature is already available via the custom launcher.

**Comment by DeadLootJ** [comment]
I am aware that is in the custom launcher, I just prefer to use the XMB. I think I may have found a workaround with the Categories Lite plugin, and making a blacklist.

**Comment by JoseAaronLopezGarcia** [comment]
Alright we can implement this feature.

**Comment by DeadLootJ** [comment]
Thank you, I really appreciate that

**Comment by JoseAaronLopezGarcia** [comment]
Done:
https://github.com/PSP-Archive/ARK-4/releases/tag/r42020
