### ISSUE TITLE
Infinity shuts down PSP after starting the installer app POST installation of ARK and Infinity

### ISSUE THREAD

**Issue by chasemc215** [PSP-Archive/ARK-4#121]
Infinity just shuts the console down after installing Infinity after ARK was installed, I'm not sure what to do.

**Comment by chasemc215** [comment]
Nevermind, I solved it myself.

**Comment by DeadLootJ** [comment]
How exactly did you solve it? I am having the same issue with my PSP Go, and I have no idea how to fix it.

**Comment by JoseAaronLopezGarcia** [comment]
> How exactly did you solve it? I am having the same issue with my PSP Go, and I have no idea how to fix it.

Run Infinity from OFW.

**Comment by DeadLootJ** [comment]
I did that with no dice, may be an issue with my Go then. Thanks for the suggestion though.

**Comment by JoseAaronLopezGarcia** [comment]
I've heard that having it on another folder makes it work. So maybe copy it elsewhere and launch it with ARK's file manager.

**Comment by DeadLootJ** [comment]
Thank you for the advice, I will try it out and see if it works.

**Comment by chasemc215** [comment]
I actually just ran ARK before opening Infinity POST installation of Infinity
