### ISSUE TITLE
Crash when trying to run Sony updater through Chronoswitch

### ISSUE THREAD

**Issue by TheSubPlayer** [PSP-Archive/ARK-4#125]
### PSP/Vita Model

PSP-3000 (Slim & Bright)

### ARK Version

4.20.33 (maybe .34 too)

### Homebrew/GAME (if applicable)

Chronoswitch 7.0

### Plugins ( if applicable )

None

### Steps to reproduce

1. Try updating/downgrading via Chronoswitch
2. The PSP will crash before the updater starts

*The PSP crashes even with all the settings below disabled, and with the ARK_1234 folder deleted
It only works when turning on the PSP via OFW (while holding <kbd>HOME</kbd> button)

### USB Charge

Always

### Overclock

Always

### Power Save

Disabled

### Autoboot Launcher

Disabled

### Disable PSP Go Pause

Disabled

### Unlock Extra Memory

Always

### Memory Stick Speedup

Always

### Inferno Cache

Always

**Comment by JoseAaronLopezGarcia** [comment]
Try this: https://github.com/PSP-Archive/ARK-4/releases/tag/v1684259777

**Comment by TheSubPlayer** [comment]
> Try this: https://github.com/PSP-Archive/ARK-4/releases/tag/v1684259777

Still crashes
