### ISSUE TITLE
Power management in custom launcher

### ISSUE THREAD

**Issue by jappoman** [PSP-Archive/ARK-4#131]
### New Feature

I would like to have the ability to reset / shutdown the console in the custom launcher with a software shortcut or a button combination of some sort (without pressing the hardware power button for 5 seconds).

Thank in advance.

**Comment by JoseAaronLopezGarcia** [comment]
Done: https://github.com/PSP-Archive/ARK-4/releases/tag/v1684412404
When going to "Exit" you'll be given a few options like shutdown and restart.
