### ISSUE TITLE
It's impossible to play via xlink kai crash tag team racing, street riders and most likely in other games, because ps vita hardware is much better than on psp. d/c(disconnect) issue or game(s) work strangely

### ISSUE THREAD

**Issue by Alexei78676** [PSP-Archive/ARK-4#141]
### New Feature

Need make the ps vita hardware work the same way as the psp and add a feature to lower and boost fps

**Comment by Alexei78676** [comment]
I will briefly formulate the question: can you make the ps vita hardware look like the hardware from the psp so that the fps is slightly similar between the two consoles?

**Comment by MotoLegacy** [comment]
Performance is already very similar to native by nature of the hybrid emulation. Stop responding to this issue.
