### ISSUE TITLE
System ahutdown when open .cso games

### ISSUE THREAD

**Issue by K-K-K-K-K-K-K-K-K** [PSP-Archive/ARK-4#145]
### PSP/Vita Model

PSP-1000 (Fat)

### ARK Version

4.20.56

### Plugins ( if applicable )

vsh, ms0:/seplugins/category_lite.prx, on

### Steps to reproduce

1.open a .cso game
2.it will show sony logo intro before crashing 
3.no problem with .iso games
4.Overclock, Memory stick speed up, and inferno cache don’t help. Turning them on doesn’t do anything

### USB Charge

Disabled

### Overclock

Disabled

### Power Save

Disabled

### Autoboot Launcher

Disabled

### Disable PSP Go Pause

Disabled

### Unlock Extra Memory

Disabled

### Memory Stick Speedup

Disabled

### Inferno Cache

Disabled

**Comment by JoseAaronLopezGarcia** [comment]
Is it only an issue with the 1K?

**Comment by JoseAaronLopezGarcia** [comment]
I cannot reproduce this issue on my 1K with any on my ISOs, neither with Testing Tool Firmware nor Retail via Time Machine.

Make sure you are actually using the latest release since this very same bug was reported, and fixed, and few releases ago.

**Comment by K-K-K-K-K-K-K-K-K** [comment]
update: I know the problem now.

I edited my backup SEPLUGIN folder and not the actual SEPLUGINS that the cfw use...

my plugin actually looked like this
`vsh, ms0:/seplugins/categorieslite/category_lite.prx, on
vsh, ms0:/seplugins/hold.prx, on
psp, ms0:/seplugins/cwcheat/cwcheat.prx, off
ULES-00151 ULUS-10041 ULES-00502 ULUS-10160, ms0:/seplugins/cwcheat/cwcheat.prx, off
ULES-00151 ULUS-10041 ULES-00502 ULUS-10160, ms0:seplugins/cheatdevice_remastered_lite.prx, on`

the problem is that the plugin cwcheat. It crashed on all .cso games, including both gta games. (ULES-00151 ULUS-10041 ULES-00502 ULUS-10160)

when I turned the plugin cwcheat completely off, the system stopped crashing.
I tested the plugin on .iso games and it work fine.

I do not know if this also happened to other psp models, as this psp 1K is my only working psp.

**Comment by JoseAaronLopezGarcia** [comment]
Strange, cwcheat works fine for me, maybe try finding a more up to date version of that plugin.
Also, cwcheat doesn't work well with GTA games if you're already using cheat device so make sure you disable it on those.

**Comment by K-K-K-K-K-K-K-K-K** [comment]
I used the same syntax as the one that was provided to specifically disable cwcheat on those two games. 

> You can also disable a plugin on certain games where they might be problematic. To do so, just add a disable line for the specific game ID after the enable line. For example, enable cwcheat on all retail games except for GTA LCS (US) and GTA VCS (EU).
> 
>     psp, ms0:/seplugins/cwcheat/cwcheat.prx, on
>     ULUS10041 ULES00502, ms0:/seplugins/cwcheat/cwcheat.prx, off

This is my config. It included those two games in both US and EU region.
`psp, ms0:/seplugins/cwcheat/cwcheat.prx, off ULES-00151 ULUS-10041 ULES-00502 ULUS-10160, ms0:/seplugins/cwcheat/cwcheat.prx`

and you're right. using vanilla cwcheat worked but 6.60ME patched version will crashed the system. My original premade cwcheat bundle likely come with that version.

And cwcheat still worked on all games. The cfw ignore my blocking. That's why gta crashed too.

**Comment by K-K-K-K-K-K-K-K-K** [comment]
Everything working now I just named game ids in the wrong format. There’s still issues with custom launcher, but the current issue is pretty much solved.
