### ISSUE TITLE
Custom Launcher not work

### ISSUE THREAD

**Issue by Kitki30** [PSP-Archive/ARK-4#163]
### PSP/Vita Model

PSP-2000 (Slim)

### ARK Version

4.20.58 pre-release

### Plugins ( if applicable )

no plugins enabled

### Steps to reproduce

press select
click custom launcher - >

### USB Charge

Always

### Overclock

Disabled

### Power Save

Disabled

### Autoboot Launcher

Disabled

### Disable PSP Go Pause

Disabled

### Unlock Extra Memory

Disabled

### Memory Stick Speedup

Disabled

### Inferno Cache

Always

**Comment by JoseAaronLopezGarcia** [comment]
I need more information.

**Comment by Kitki30** [comment]
@JoseAaronLopezGarcia 
I just clicked select to go to vsh menu clicked custom launcher and it was loading my games but it loaded 2 games and screen freezes after 10 secounds psp turns of and makes pop sound

**Comment by JoseAaronLopezGarcia** [comment]
Seems like one of the games is causing it to crash, try moving them all to another folder then move one by one until you find the one that crashes.

**Comment by Kitki30** [comment]
ok but i have 100+ games it can be hard but i will try

**Comment by JoseAaronLopezGarcia** [comment]
You can always move them over to other folders and use the File Browser to launch them.

**Comment by Kitki30** [comment]
@JoseAaronLopezGarcia
Fixed it was one game from itch

**Comment by JoseAaronLopezGarcia** [comment]
so there's a game that causes the launcher to crash? which game is it?

**Comment by Kitki30** [comment]
glitch (i found it on itch.io)
i dont know if a can send links here but google glitch psp itch.io and you can find it
