### ISSUE TITLE
ARK Launcher: Start Button behavior in files-browser

### ISSUE THREAD

**Issue by svensvond** [PSP-Archive/ARK-4#166]
### New Feature

Would it be possible to not only have the start-button run the assigned behaviour in the "Games"  navigation but also in the "Files" browser? Since i have files navigation as default, i could press start also in here to run the recent / random game.

**Comment by JoseAaronLopezGarcia** [comment]
ok

**Comment by JoseAaronLopezGarcia** [comment]
https://github.com/PSP-Archive/ARK-4/releases/tag/v1687943030
(same pre-release as the other thread).
