### ISSUE TITLE
ARK Launcher: Hide files / folders with hidden attribute in files-browser

### ISSUE THREAD

**Issue by svensvond** [PSP-Archive/ARK-4#167]
### New Feature

I do not want the user (the kids ;) ) to see different folders / files in the file-browser. I can set the hidden attribute in - for example -windows, but it has no affect.

**Comment by JoseAaronLopezGarcia** [comment]
It doesn't seem like the PSP IO layer has support for Windows-style file attributes but rather it uses a more UNIX approach.

This means to implement this I have to implement it the UNIX way: "normalfile.iso" -> ".hiddenfile.iso"
Placing a dot at the start of the file/folder is considered "hidden" in UNIX, and that's pretty easy to implement.

I will also have to implement an option in the settings menu to "Show Hidden".

**Comment by JoseAaronLopezGarcia** [comment]
here you go: https://github.com/PSP-Archive/ARK-4/releases/tag/v1687945858

**Comment by svensvond** [comment]
Ok, looks good.
There is no option but to rename the files / folders? ok.
But maybe the apps / games could also be hidden in the game-view, currently it can be stilled accessed there.

**Comment by JoseAaronLopezGarcia** [comment]
> Ok, looks good. There is no option but to rename the files / folders? ok. But maybe the apps / games could also be hidden in the game-view, currently it can be stilled accessed there.

If you rename /ISO/ to /.ISO/ you won't see them in the game section, only in the browser if you enable "Show Hidden".
Same for /PSP/GAME/ to /PSP/.GAME/ though instead of doing that to /PSP/GAME/ I would use /PSP/APPS/ instead (which the Launcher is compatible with).

**Comment by svensvond** [comment]
i have inside /PSP/GAME folders like LME .lme_installer and want this to be hidden in games overview

**Comment by JoseAaronLopezGarcia** [comment]
ok hold on I'll get around to it once I finish making some cool changes to the file browser (you're gonna like them).

**Comment by svensvond** [comment]
:)

**Comment by JoseAaronLopezGarcia** [comment]
Here you go: https://github.com/PSP-Archive/ARK-4/releases/tag/v1688039004
Game should now also be hidden if they start with a '.', I've also improved the file browser when it comes to viewing and launching games, so you might want to go around your ISO folder and let me know what you think.

**Comment by JoseAaronLopezGarcia** [comment]
Ok I've added the option to disable ICON0 in Browser and also made it use the Skip GameBoot feature and the Start button for Current game, you have all those options so you can leave it to your linking.

**Comment by svensvond** [comment]
nice.

**Comment by svensvond** [comment]
initially there where no ICON0 in Browser showing, i toggled skipgameboot option: Now i cant get rid of the ICON0 image display in browser any more - what happened? I even deleted the settings file: Images in Filebrowser are still beeing loaded. I dont see any option to just turn off ICON0 display. I dont see any explicit option for turning images on and off either.

**Comment by JoseAaronLopezGarcia** [comment]
Update to latest pre-release.

**Comment by svensvond** [comment]
works like a charm - maybe one tiny little thing. I really like the "game boot preview thing" in file browser! Could you bind that to a key, for example right trigger in any case? So that if you want to quick start press X or RIGHT TRIGGER for game boot.

**Comment by svensvond** [comment]
ok, had start button set to "last game" .. but yes, this works.
