### ISSUE TITLE
RetroArch 1.10.2 crashes when trying to launch a rom

### ISSUE THREAD

**Issue by McFly75** [PSP-Archive/ARK-4#17]

**Comment by krazynez** [comment]
Is this on the GO? I have tested this on the 1K (Phat) and it is working fine.

**Comment by McFly75** [comment]
No on a PSP 3000. Will do some more testing. From: krazynezSent: 24. marts 2022 21:24To: PSP-Archive/ARK-4Cc: McFly75; AuthorSubject: Re: [PSP-Archive/ARK-4] RetroArch 1.10.2 crashes when trying to launch a rom (Issue #17) Is this on the GO? I have tested this on the 1K (Phat) and it is working fine.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by McFly75** [comment]
OK, did some more testing on my PSP 3000, with different rom & different cores and "all" seems to be working now.
