### ISSUE TITLE
Can’t install ark-4

### ISSUE THREAD

**Issue by hozluvice** [PSP-Archive/ARK-4#172]
### PSP/Vita Model

PSP-2000 (Slim)

### ARK Version

latest

### Steps to reproduce

trying to install ark-4 with previous 6.61 PROMOD-C2p infinity followed youtube step by step and will not have the new ark-4

### USB Charge

Disabled

### Overclock

Disabled

### Power Save

Disabled

### Autoboot Launcher

Disabled

### Disable PSP Go Pause

Disabled

### Unlock Extra Memory

Disabled

### Memory Stick Speedup

Disabled

### Inferno Cache

Disabled

**Comment by svensvond** [comment]
Please describe the exact technical problem (e.g. error messages) 
Also use "Steps to reproduce" as a detailed workflow description

**Comment by hozluvice** [comment]
I did this exact following procedure of this video https://youtu.be/bE8mw7RRqGo

I load up the ark loader, I then install it throught infinity once Install I reboot the psp but ark 4 does not appear on recovery menu nor new menus appear

**Comment by krazynez** [comment]
> I did this exact following procedure of this video https://youtu.be/bE8mw7RRqGo
> 
> I load up the ark loader, I then install it throught infinity once Install I reboot the psp but ark 4 does not appear on recovery menu nor new menus appear

Please provide exact steps taken. It will help us out more than linking to a video.

**Comment by JoseAaronLopezGarcia** [comment]
Make sure you boot Infinity again to enable ARK.

**Comment by JoseAaronLopezGarcia** [comment]
has this been solved?

**Comment by hozluvice** [comment]
Yes
