### ISSUE TITLE
No key for update check

### ISSUE THREAD

**Issue by Kitki30** [PSP-Archive/ARK-4#173]
### PSP/Vita Model

PSP-2000 (Slim)

### ARK Version

4.20.59

### Homebrew/GAME (if applicable)

Launcher

### Steps to reproduce

1. Open custom launcher 
2. Press triangle
3. Go to Network
4. And you see Press [] to check updates and if you start ftp server you can see FTP Server is running @ 192.168.0.17. Press () to stop and also Press [] to check for updates

### USB Charge

Always

### Overclock

Disabled

### Power Save

Disabled

### Autoboot Launcher

Disabled

### Disable PSP Go Pause

Disabled

### Unlock Extra Memory

Disabled

### Memory Stick Speedup

Disabled

### Inferno Cache

Always

**Comment by Kitki30** [comment]
My point is that there is no button in place of [] and ().

**Comment by JoseAaronLopezGarcia** [comment]
I don't understand what you mean here. It's working as intended.

**Comment by krazynez** [comment]
> My point is that there is no button in place of [] and ().

Do you mean have images of the buttons instead of text?

**Comment by Kitki30** [comment]
yes image of button instead of []

**Comment by Kitki30** [comment]
@krazynez

**Comment by krazynez** [comment]
How is this a bug?

**Comment by Kitki30** [comment]
no button showed

**Comment by krazynez** [comment]
There is no button its just text

**Comment by JoseAaronLopezGarcia** [comment]
It would be extremely complicated to do this unless the PSP's font has the PS buttons in it. I'm not sure, might have to look at how the XMB does it.
