### ISSUE TITLE
Add sliding text to some translations

### ISSUE THREAD

**Issue by Kitki30** [PSP-Archive/ARK-4#175]
some text looks ugly on translations

![IMG_20230701_114509.jpg](https://github.com/PSP-Archive/ARK-4/assets/84147906/aa6af9b0-62df-4d52-9753-3f9822048481)

![IMG20230701114551.jpg](https://github.com/PSP-Archive/ARK-4/assets/84147906/7f689a49-1ae7-4c86-aa0d-6bc6a6c1bdf9)

![IMG20230701114745.jpg](https://github.com/PSP-Archive/ARK-4/assets/84147906/49d05400-a4e7-460e-a894-7132d960442a)

**Comment by JoseAaronLopezGarcia** [comment]
Fixed on latest pre-release: https://github.com/PSP-Archive/ARK-4/releases/tag/v1688220069
