### ISSUE TITLE
UMD crashed custom launcher

### ISSUE THREAD

**Issue by Kitki30** [PSP-Archive/ARK-4#176]
### PSP/Vita Model

PSP-2000 (Slim)

### ARK Version

4.20.59

### Homebrew/GAME (if applicable)

idk but i think its UCES-00356

### Steps to reproduce

Go to custom launcher
Insert the UMD
qait 5 seconds
and psp crashes and turns off

### USB Charge

Always

### Overclock

Disabled

### Power Save

Disabled

### Autoboot Launcher

Disabled

### Disable PSP Go Pause

Disabled

### Unlock Extra Memory

Always

### Memory Stick Speedup

Disabled

### Inferno Cache

Always

**Comment by Kitki30** [comment]
UMD
![16882053147945857860558611557185](https://github.com/PSP-Archive/ARK-4/assets/84147906/f3c31058-5ee2-40ae-9e81-eb80aee17c4f)

**Comment by JoseAaronLopezGarcia** [comment]
fixed in latest pre-release
