### ISSUE TITLE
Recovery USB access 

### ISSUE THREAD

**Issue by Jambul46** [PSP-Archive/ARK-4#182]
### New Feature

As title.

**Comment by JoseAaronLopezGarcia** [comment]
already available in pre-release (4.20.60 beta)

**Comment by Jambul46** [comment]
Oh sorry then. Iam currently on 4.20.59

**Comment by JoseAaronLopezGarcia** [comment]
It's ok, I don't expect people to know about this feature until it gets properly released.

**Comment by krazynez** [comment]
soon 😉
