### ISSUE TITLE
6.60 Testing Tool fw support for Newcipl.

### ISSUE THREAD

**Issue by reminon** [PSP-Archive/ARK-4#184]
### New Feature

Can we get get newcipl support for the 6.60TT firmware?
Would prefer cipl over infinity. If possible.

**Comment by JoseAaronLopezGarcia** [comment]
The classic cIPL works just fine. At least on my 1K converted to 6.60 TT.

**Comment by reminon** [comment]
Ok thanks. Didn't wanna risk it without clarification.

**Comment by JoseAaronLopezGarcia** [comment]
You're right, I probably should clarify it on the readme.
