### ISSUE TITLE
Some folders are recognized as files, making it impossible to open them

### ISSUE THREAD

**Issue by TheSubPlayer** [PSP-Archive/ARK-4#186]
### PSP/Vita Model

PSP-3000 (Slim & Bright)

### ARK Version

4.20.60 r6

### Homebrew/GAME (if applicable)

Custom Launcher

### Steps to reproduce

Idk how to reproduce, it just happened 

![IMG_20230708_221939252~01](https://github.com/PSP-Archive/ARK-4/assets/110436924/1174f613-5395-458c-a19e-77353fe2991c)
![IMG_20230708_221912173~01](https://github.com/PSP-Archive/ARK-4/assets/110436924/390e0c26-2bcb-45fb-a10c-5c2677e9286b)

### USB Charge

Always

### Overclock

Always

### Power Save

Disabled

### Autoboot Launcher

Disabled

### Disable PSP Go Pause

Disabled

### Unlock Extra Memory

Always

### Memory Stick Speedup

Always

### Inferno Cache

Always

**Comment by JoseAaronLopezGarcia** [comment]
Check latest revision, this should be fixed.

**Comment by TheSubPlayer** [comment]
Yeah, it's fixed
