### ISSUE TITLE
Custom Launcher & Category Lite (Folders) do not work 

### ISSUE THREAD

**Issue by McFly75** [PSP-Archive/ARK-4#19]
Games/Apps in folder do not show.

**Comment by Kalanyr** [comment]
This is a bit if a problem on Vita particularly since the default entry is into the Custom Launcher rather than the XMB so items sorted into categories for eg use on Adrenaline become unavailable.

**Comment by JoseAaronLopezGarcia** [comment]
Will look into this.

**Comment by JoseAaronLopezGarcia** [comment]
Fixed in version 4.18.3:
https://github.com/PSP-Archive/ARK-4/releases/tag/r183

You can enable the option to scan category entries in the settings menu.
