### ISSUE TITLE
Satelite menu displays `ё` as `±`

### ISSUE THREAD

**Issue by jeffangelion** [PSP-Archive/ARK-4#191]
### PSP/Vita Model

PSP-2000 (Slim)

### ARK Version

4.20.61 Rev 2

### Steps to reproduce

1. Select system language as Russian (Русский)
2. Press "Select" button in XMB menu
3. Select "РАСШИРЕННОЕ VSH МЕНЮ" (ADVANCED VSH MENU)
4. Scroll through "ЦВЕТА ВЫДЕЛЕНИЯ" (FG COLORS) options
5. See "Ж±лтый","Прозрачно-ж±лтый","Зел±ный","Прозрачно-зел±ный","Ч±рный","Прозрачно-ч±рный" instead of "Жёлтый","Прозрачно-жёлтый","Зелёный","Прозрачно-зелёный","Чёрный","Прозрачно-чёрный"

Possible affected files:
[satelite_ru.txt (CP866 encoded)](https://github.com/PSP-Archive/ARK-4/blob/main/extras/menus/arkMenu/themes/translations/resources/satelite_ru.txt)
[CP866.pf](https://github.com/PSP-Archive/ARK-4/blob/main/extras/menus/arkMenu/themes/translations/resources/CP866.pf)

### USB Charge

Always

### Overclock

Always

### Power Save

Disabled

### Autoboot Launcher

Disabled

### Disable PSP Go Pause

Disabled

### Unlock Extra Memory

Disabled

### Memory Stick Speedup

Always

### Inferno Cache

Always

**Comment by krazynez** [comment]
Do you mind translating this to be proper then: https://github.com/PSP-Archive/ARK-4/blob/main/extras/menus/arkMenu/themes/translations/resources/satelite_ru.txt

Translates are very much appreciated :+1:

**Comment by jeffangelion** [comment]
There is no problem with locale itself, looks like it's font problem

**Comment by jeffangelion** [comment]
As far as I can see, there is collision between CP866 and CP437 at 0xF1 (code for both symbols), so there are two options:
1. Fix font by adding `ё` symbol to prevent CP437 fallback
2. Change all `ё` occurrences by `е` (still understandable yet incorrect)

However, in `CYRIL_B.pf` font `ё` symbol is presented yet it has CP866-incompatible codemap
Does anyone know font structure or tool for them?

**Comment by JoseAaronLopezGarcia** [comment]
I believe @pyroesp was investigating the format of the fonts. I'll ask what details are known about them.

**Comment by jeffangelion** [comment]
AFAIK, .pf font is a raw monochrome bitmap of 16x16 symbols of size 8x8 pixels

**Comment by jeffangelion** [comment]
I did a small redraw of RUSSIAN.pf to make it CP866 complaint, should I open PR to replace it or add as option?
![image](https://github.com/PSP-Archive/ARK-4/assets/16368461/09bd36bd-b777-4bde-bb41-c6b3feb6fbc9)

**Comment by jeffangelion** [comment]
Offtopic: CYRIL_B.pf so gibberish
![image](https://github.com/PSP-Archive/ARK-4/assets/16368461/8d1efe88-63bc-4d14-af58-90f12fa22675)

**Comment by jeffangelion** [comment]
Okay, I fixed all Cyrillic fonts, gotta make PR by this week

**Comment by pyroesp** [comment]
I've been working a little bit on a simple font editor as a homebrew for ARK.
Haven't been able to finish it yet 🙏🏻 .

Thanks for fixing the fonts 👍🏻 .

**Comment by jeffangelion** [comment]
@pyroesp i made two simple python scripts for pf <-> png conversions, i'll include them in commit message

**Comment by jeffangelion** [comment]
<details><summary>It works</summary>

![изображение](https://github.com/PSP-Archive/ARK-4/assets/16368461/55763402-214f-4dd9-8daf-d8a6ba2ec28a)
</details>
