### ISSUE TITLE
Codecs for psp media player

### ISSUE THREAD

**Issue by cyberbasty** [PSP-Archive/ARK-4#212]
### New Feature

If possible, I would like to see a Flac (or even other formats) codec for the xmb music player.
Thank you for reading my post and providing a response ;)

**Comment by JoseAaronLopezGarcia** [comment]
I'm not sure about the XMB but we might be able to implement it on the Custom Launcher.

**Comment by JoseAaronLopezGarcia** [comment]
https://github.com/PSP-Archive/ARK-4/issues/169
