### ISSUE TITLE
Faster custom launcher when many games installed

### ISSUE THREAD

**Issue by McFly75** [PSP-Archive/ARK-4#213]
### New Feature

Is it possible to make the custom Launcher work faster when many games is installed.

I have a 128GB card with some emulators, homebrew, PS1 and a lot of PSP/PSP Minis.
But that slows down the Custom Launcher a lot.
For now I just use the standard launcher with categories Lite and some folders like A-C, D-K, PSP Minis etc.
But as the custom Launcher does not use/work with folders, it has to load all the icons.

Maybe a cache system where it casches the icons and you must manually reload (using Start) when adding or removing new games. Then it would only be the first time or when ever you manually refresh the games list, it takes a lot of time.

Or the launcher only loads the 25 first PSP games or something like that, perhaps a options in setting where you can choose how many PSP games it should load.

**Comment by JoseAaronLopezGarcia** [comment]
Try using the File Browser instead of the Games Manager, you can set the File Browser to be the main menu so it will load faster.
