### ISSUE TITLE
Inferno Cache: LRU vs RR difference?

### ISSUE THREAD

**Issue by McFly75** [PSP-Archive/ARK-4#214]
### New Feature

Inferno Cache: What is the difference between LRU and RR?

Is one better/faster/more compatible than the other?

**Comment by krazynez** [comment]
RR is an algorithm that is time based. LRU uses an algorithm to removes the least recently used (LRU) from cache. From my testing I have not seen a diffrence but your milage may very.

**Comment by krazynez** [comment]
Reference: https://github.com/PSP-Archive/ARK-4/issues/215#issuecomment-1694719609
