### ISSUE TITLE
Balanced Energy Mode? What does it do?

### ISSUE THREAD

**Issue by McFly75** [PSP-Archive/ARK-4#215]
### New Feature

What does the Balanced Energy Mode do?

Does it set a specific Clock/men speed?

**Comment by krazynez** [comment]
Yes sets the PSP to default clock speeds 222/111

**Comment by krazynez** [comment]
If you will instead of opening Issues on the GitHub page for questions, you can join the discord server and ask in `#support` or in `#ark-cfw` [PSP Homebrew Discord](https://discord.gg/bePrj9W). :+1:
