### ISSUE TITLE
psp slow to start (how to disable UMD?)

### ISSUE THREAD

**Issue by freelancers19** [PSP-Archive/ARK-4#223]
### PSP/Vita Model

PSP-2000 (Slim)

### ARK Version

4.20.63 Rev 2

### Homebrew/GAME (if applicable)

noumd

### Plugins ( if applicable )

vhs, ms0:/seplugins/noumd.prx, on
game, ms0:/seplugins/noumd.prx, on

### Steps to reproduce

PSP is slow to start up. I want to disable reading from the UMD, I tried to install the NoUMD plugin, but it doesn't work on Ark-4 4.20.63 Rev 2. How can I fix it?

### USB Charge

Disabled

### Overclock

Disabled

### Power Save

Disabled

### Balanced Energy Mode

Disabled

### Autoboot Launcher

Off

### Disable PSP Go Pause

Off

### Unlock Extra Memory

Disabled

### Memory Stick Speedup

Disabled

### Inferno Cache

Off

### Skip Sony Logos

Off

### Hide PIC0 and PIC1

Off

### Hide MAC Address

Off

### Hide DLC

Off

### Turn off LEDs

Disabled

**Comment by freelancers19** [comment]
I have solved. I was wrong to write "VSH"
it works

**Comment by krazynez** [comment]
Okay good thanks for the update.
