### ISSUE TITLE
Text spacing in Network menu (ARK CL)

### ISSUE THREAD

**Issue by Jambul46** [PSP-Archive/ARK-4#224]
### PSP/Vita Model

PSP-3000 (Slim & Bright)

### ARK Version

Latest*

### Homebrew/GAME (if applicable)

ARK Custom Launcher

### Steps to reproduce

Open Network menu in CL and overfill text window 
The last line goes under the screen

### USB Charge

Always

### Overclock

Homebrew

### Power Save

Disabled

### Balanced Energy Mode

Game

### Autoboot Launcher

Off

### Disable PSP Go Pause

Off

### Unlock Extra Memory

Disabled

### Memory Stick Speedup

Alway

### Inferno Cache

Off

### Skip Sony Logos

On

### Hide PIC0 and PIC1

Off

### Hide MAC Address

Off

### Hide DLC

Off

### Turn off LEDs

Disabled

**Comment by JoseAaronLopezGarcia** [comment]
Yes, he's probably using FTP. This issue may have come from adding the "Press [] To update" line without adjusting the maximum amount of lines it can display. So if it had a maximum of 10, it'll draw 11 instead.

**Comment by JoseAaronLopezGarcia** [comment]
Should be fixed in latest pre-release.
