### ISSUE TITLE
loading umd video iso causes xmb to fail to load

### ISSUE THREAD

**Issue by joshknobloch2** [PSP-Archive/ARK-4#227]
### PSP/Vita Model

PSP-1000 (Fat)

### ARK Version

4.20.64 r1

### Homebrew/GAME (if applicable)

akira umd video 

### Plugins ( if applicable )

Game, hud-go.prx, off
Always, cdda_enabler.prx, on
XMB, XMBIH.prx, on
Xmb, cxmb.prx, on
Always, bright3.prx, on
Always, hold.prx, on
Always, pspowersaver.prx, on
Xmd, category_lite.prx, on

### Steps to reproduce

1. Open VSH, advanced VSH
2. Select video iso, press x to confirm
3. Let xmb reload
4. No icons, no MS activity. VSH menu does open. Resetting VSH without iso video returns system to normal. Reset device option does nothing.
-----
1. Open Custom Launcher
2. Open file manager
3. Navigate to iso video
4. Select iso video
5. System loads into xmb, without any icons and no ms activity. VSH opens, resetting VSH returns system to normal. Reset device option does nothing.
-----
Other settings - have tested with and without umd drive being disabled.

### USB Charge

Disabled

### Overclock

Game

### Power Save

Disabled

### Balanced Energy Mode

XMB

### Autoboot Launcher

Off

### Disable PSP Go Pause

Off

### Unlock Extra Memory

Disabled

### Memory Stick Speedup

Alway

### Inferno Cache

LRU

### Skip Sony Logos

Off

### Hide PIC0 and PIC1

On

### Hide MAC Address

On

### Hide DLC

On

### Turn off LEDs

Disabled

**Comment by JoseAaronLopezGarcia** [comment]
Fixed in latest revision.
