### ISSUE TITLE
Pacman World 3 crashes the PSP (on Release 14.1, no plugins, works with Pro-C2)

### ISSUE THREAD

**Issue by McFly75** [PSP-Archive/ARK-4#23]
Pacman World 3 crashes the PSP (on Release 14.1, no plugins, works with Pro-C2)
Tested on a PSP 3000 and a PSP GO, with plugins disabled, tried both cso and iso.
When starting the game, screen turns black and PSP shots down after a few seconds.
Works fine with PRO-C2 cfw, don´t know why???

**Comment by krazynez** [comment]
DEBUG version PSPLINK output 4.14.4 
```
host0:/> syspatch: PMA(0x0123)
Loading all modules ... Ready
0: 
bkHostAppendFile: Open host0: failed - sleeping
bkHostAppendFile: Open host0: failed - sleeping
bkHostAppendFile: Open host0: failed - sleeping
bkHostAppendFile: Open host0: failed - sleeping
bkHostAppendFile: Open host0: failed - sleeping
bkHostAppendFile: Open host0: failed - sleeping
bkHostAppendFile: Open host0: failed - sleeping
bkHostAppendFile: Open host0: failed - sleeping
.....
```

**Comment by krazynez** [comment]
update: Works from ArkMenu (Custom Launcher) looking into why it won't from xmb however.

**Comment by krazynez** [comment]
latest pre-release fixes this issue: https://github.com/PSP-Archive/ARK-4/releases/tag/v1649190604

**Comment by McFly75** [comment]
Weird, but will still not work on my PSP 3000 (both cso & iso)
v1649245439

**Comment by JoseAaronLopezGarcia** [comment]
Can you try with latest release?
https://github.com/PSP-Archive/ARK-4/releases/tag/r145

**Comment by McFly75** [comment]
Tried Version 4.14.5, and it still crashes the PSP 3000.
But it does work fine when launched using the AKR-4 Custom Launcher.

**Comment by McFly75** [comment]
Sorry my bad, Pacman World 3 works fine now on Version 4.14.5
I was only replacing the SAVEDATA ARK_01234
& not replacing/running ARK_Live again.
