### ISSUE TITLE
Unable to find the NoDRM Engine setting

### ISSUE THREAD

**Issue by Goldtuga** [PSP-Archive/ARK-4#231]
### New Feature

Where can I find the NoDRM Engine setting to be able to run DLC? Also, even if finding it and enabling it, will one have to manually download and set a plugin and/or use ISO Tool to run some DLC, like LittleBigPlanet's? 

EDIT: Any of my PSP DLC don't work, regardless if they are in the root of the GAME folder or in the SAVEDATA one. They don't even work in Adrenaline even with the NoDRM Engine setting enabled.

**Comment by JoseAaronLopezGarcia** [comment]
The NoDRM engine is NOT for DLC loading. For that you need `nploader` plugin.
There is no setting to disabled NoDRM engine, it's always active.

**Comment by Goldtuga** [comment]
But it was in Pro-CFW ans there was DLC that needed the NoDRM engine to be disabled in order to work.

Also, how can I make ARK read PSP DLC in the form of save data and specific DLC like LittleBigPlanet's? The games don't even detect the save data even though they share the same region.

**Comment by JoseAaronLopezGarcia** [comment]
ARK doesn't let you disable the NoDRM engine as there is no real reason to do this. On PRO it could clash with other plugins, this is not an issue with ARK.

**Comment by Goldtuga** [comment]
> ARK doesn't let you disable the NoDRM engine as there is no real reason to do this. On PRO it could clash with other plugins, this is not an issue with ARK.

How can I make ARK read PSP DLC in the form of save data and specific DLC like LittleBigPlanet's? The games don't even detect the save data even though they share the same region.
