### ISSUE TITLE
Doubt about the NoPspEmuDrm plugin

### ISSUE THREAD

**Issue by Goldtuga** [PSP-Archive/ARK-4#233]
### PSP/Vita Model

PCH-2000 (Vita Slim)

### ARK Version

4.20.64 Rev 4

### Steps to reproduce

When iARK's GitHub says to download and install the NoPspEmuDrm plugin and that one can use AutoPlugin II to do it, is it referring to AutoPlugin II's NoNpDrm Unofficial or to AutoPlugin II's npdrm libre (this one in the Adrenaline plugins section)? If to one of these two, may one remove (or not even install) the other one?

### USB Charge

Disabled

### Overclock

Disabled

### Power Save

Disabled

### Balanced Energy Mode

Disabled

### Autoboot Launcher

Off

### Disable PSP Go Pause

Off

### Unlock Extra Memory

Disabled

### Memory Stick Speedup

Disabled

### Inferno Cache

Off

### Skip Sony Logos

Off

### Hide PIC0 and PIC1

Off

### Hide MAC Address

Off

### Hide DLC

Off

### Turn off LEDs

Disabled

**Comment by krazynez** [comment]
Good point it is this one: `NoPspEmuDrm by SilicaAndPina`

also changed it via Readme and Wiki as well to state which one.

**Comment by Goldtuga** [comment]
> Good point it is this one: `NoPspEmuDrm by SilicaAndPina`
> 
> also changed it via Readme and Wiki as well to state which one.

But that plugin isn't available in AutoPlugin II so should one download it from the link mentioned in ARK's GitHub?

**Comment by krazynez** [comment]
![2023-09-16-104937](https://github.com/PSP-Archive/ARK-4/assets/39999447/dadcf1f2-281e-44f0-b399-4ec6469625d5)
 Yes it is.

**Comment by Goldtuga** [comment]
> ![2023-09-16-104937](https://user-images.githubusercontent.com/39999447/268454556-dadcf1f2-281e-44f0-b399-4ec6469625d5.jpg) Yes it is.

You're right. Should I install it and keep NoNpDrm Unofficial or may I remove the latter? Do they do the same thing? Also, I found out there are now two plugins in AutoPlugin II's PSP section: Npdrm free by qwikrazor87 and Npdrm free by qwikrazor87, modified by lusid1. Are they both needed or just one of them?

**Comment by krazynez** [comment]
That is the only one that is Officially supported.

**Comment by Goldtuga** [comment]
> That is the only one that is Officially supported.

What do you mean? 

Anyway, I've been installing ARK on the PS Vita via the FasterARK method without installing the NoPspEmuDrm plugin and it has been working.

**Comment by krazynez** [comment]
> > That is the only one that is Officially supported.
> 
> What do you mean?
> 
> Anyway, I've been installing ARK on the PS Vita via the FasterARK method without installing the NoPspEmuDrm plugin and it has been working.

The one we say in the README & Wiki is the only one that is officially supported for ARK-4.

**Comment by Goldtuga** [comment]
> > > That is the only one that is Officially supported.
> > 
> > 
> > What do you mean?
> > Anyway, I've been installing ARK on the PS Vita via the FasterARK method without installing the NoPspEmuDrm plugin and it has been working.
> 
> The one we say in the README & Wiki is the only one that is officially supported for ARK-4.

So, does it do a different thing than the NoNpDrm Unnoficial plugin, then?

**Comment by Goldtuga** [comment]
> > > That is the only one that is Officially supported.
> > 
> > 
> > What do you mean?
> > Anyway, I've been installing ARK on the PS Vita via the FasterARK method without installing the NoPspEmuDrm plugin and it has been working.
> 
> The one we say in the README & Wiki is the only one that is officially supported for ARK-4.

What's the difference between AutoPlugin II's PSP Npdrm free by qwikrazor87 and Npdrm free by qwikrazor87, modified by lusid1 plugins?

**Comment by krazynez** [comment]
I do not know about other plugins, just the ones we support.

**Comment by Goldtuga** [comment]
> I do not know about other plugins, just the ones we support.

I gues the latter needs nploader.
