### ISSUE TITLE
USB connection in the custom launcher

### ISSUE THREAD

**Issue by jappoman** [PSP-Archive/ARK-4#245]
### New Feature

As the title says, is it possible to have the ability to enable the usb connection while in the custom launcher? Or maybe an option in recovery to always have it enabled when in custom launcher.

**Comment by JoseAaronLopezGarcia** [comment]
Go to File Browser, press L button to open option menu, you'll see the option to enable/disable USB.
This option only works on PSP and Adrenaline, it isn't available on Standalone Vita installations.

**Comment by jappoman** [comment]
Sorry mate didnt know about that. Thank you very much.
