### ISSUE TITLE
CSO Shutoff From Memory stick

### ISSUE THREAD

**Issue by PSPGOENTHUSIAST** [PSP-Archive/ARK-4#249]
### PSP/Vita Model

PSP-N1000 (PSP Go)

### ARK Version

4.20.65 r3

### Homebrew/GAME (if applicable)

All CSO Games from Memory Stick

### Plugins ( if applicable )

xmb, ef0:/seplugins/CXMB/CXMB.PRX, on

game, ef0:/seplugins/CWCHEAT/cwcheat.prx, on

ps1, ef0:/seplugins/CWCHEAT/cwcheatpops.prx, on

game, ef0:/seplugins/nploader.prx, off

ps1, ef0:/seplugins/cdda_enabler.prx, on

ULUS10160, ef0:/seplugins/CWCHEAT/cwcheat.prx, off

ULUS10160, ef0:/seplugins/cheatdevice_remastered.prx, on

always, ef0:/seplugins/brightness.prx, on

xmb, ef0:/seplugins/category_lite.prx, on

### Steps to reproduce

Attemping to launch any CSO formatted game stored on my memory stick from either the xmb or the custom launcher results in my PSP go shutting off.

Extra details:
Homebrew, iso files and PS1 eboots still launch and work from memory stick. The CSO games do work from memory stick when being ran under lme 2.3 CFW with the same plugin setup. CSO files were compressed using umdgen with compression level 9 selected. 

### USB Charge

Disabled

### Overclock

Disabled

### Power Save

Disabled

### Balanced Energy Mode

Disabled

### Autoboot Launcher

Off

### Disable PSP Go Pause

Off

### Unlock Extra Memory

Disabled

### Memory Stick Speedup

Alway

### Inferno Cache

Off

### Skip Sony Logos

Off

### Hide PIC0 and PIC1

Off

### Hide MAC Address

Off

### Hide DLC

Off

### Turn off LEDs

Disabled

**Comment by JoseAaronLopezGarcia** [comment]
Unfortunately I can't seem to be able to reproduce this. Do you know the exact release that broke it?

**Comment by PSPGOENTHUSIAST** [comment]
It hasn't ever worked for the past few days and even after a few updates still nothing. One thing I forgot to mention is that I am using an internal 128gb SD to memory stick adapter. If all else fails, I could get them all as iso files

**Comment by JoseAaronLopezGarcia** [comment]
It only affects CSO? ISO works fine?

**Comment by PSPGOENTHUSIAST** [comment]
Yes only CSO. Although the ISO loads slow but that's probably due to the 128gb size

**Comment by PSPGOENTHUSIAST** [comment]
It was not formatted with the psp itself. It shouldn't be fragmented as it's a new card. I've read only that the only issue is longer xmb load times. I sure hope it hasn't gone fairly since it's only about a year old ordered from Etsy. 

I'll format it using the PSP and re copy everything and see what happens. Any way to make the xmb or custom launcher cache the games to reduce load times?

**Comment by JoseAaronLopezGarcia** [comment]
The XMB already uses a cache for ISO files.

**Comment by PSPGOENTHUSIAST** [comment]
After formatting using the PSP I still can't get CSO files to work. I'll just convert them to iso

**Comment by JoseAaronLopezGarcia** [comment]
Try using ZSO or JSO, they are very fast.

**Comment by PSPGOENTHUSIAST** [comment]
What windows programs can create those?

**Comment by krazynez** [comment]
https://github.com/PSP-Archive/ARK-4/tree/main/contrib/PC/ciso

**Comment by PSPGOENTHUSIAST** [comment]
Thanks. Any difference between zso or jso?

**Comment by JoseAaronLopezGarcia** [comment]
- Maxcso can create CSO, ZSO and DAX files of any block size but it's only command-line.
- PSP ISO Compressor v1.4 supports CSO, JSO and DAX with a nice GUI but doesn't allow changing block size.
- PSXiSO is a recently made GUI app that can compress ISO to CHD and ZSO.

As for JSO vs ZSO vs CSO vs DAX:
- ZSO is the fastest but has the worst compression.
- CSO and DAX are the slowest but have better compression.
- JSO is a middle ground, better speed than CSO and better compression than ZSO.

**Comment by PSPGOENTHUSIAST** [comment]
Perfect thanks I'll try them

**Comment by JoseAaronLopezGarcia** [comment]
If speed really is a must then you have to go for ZSO with 8K blocks, even if compression isn't as good as other formats (it's still better/smaller than ISO in most cases, while maintaining ISO speeds).

The only app that lets you create these is maxcso, which is a command-line tool.

**Comment by PSPGOENTHUSIAST** [comment]
Can you give me the command to create a zso with 8k blocks using Maxcso? I'm not the best with command line

**Comment by JoseAaronLopezGarcia** [comment]
it should be something like this:

maxcso --block=8192 --format=zso "My Game.iso"

**Comment by PSPGOENTHUSIAST** [comment]
I see. I just figured it out with jiso.exe. Should I still use Maxcso instead?

**Comment by JoseAaronLopezGarcia** [comment]
Try both and stick to whichever works best for you.

**Comment by PSPGOENTHUSIAST** [comment]
Is the compression algorithm for zso on jiso lzo or zlib?

**Comment by JoseAaronLopezGarcia** [comment]
jiso is for JSO not for ZSO

**Comment by PSPGOENTHUSIAST** [comment]
Gotcha. Jso files do boot from memory card

**Comment by PSPGOENTHUSIAST** [comment]
Unrelated but do y'all have a discord so I don't flood your GitHub page with issues or ideas?

**Comment by krazynez** [comment]
> Unrelated but do y'all have a discord so I don't flood your GitHub page with issues or ideas?

Appreciate that: We are apart of the [PSP Homebrew Community](https://discord.gg/bePrj9W) discord

**Comment by JoseAaronLopezGarcia** [comment]
> > Unrelated but do y'all have a discord so I don't flood your GitHub page with issues or ideas?
> 
> Appreciate that: We are apart of the [PSP Homebrew Community](https://discord.gg/bePrj9W) discord

We should put this link somewhere easy to find.

**Comment by PSPGOENTHUSIAST** [comment]
Technically I still can't use CSO files but zso are much better so we can consider this solved. Probably just an issue with my setup

**Comment by krazynez** [comment]
verified OP stated can close via Discord
