### ISSUE TITLE
Discord Server Link

### ISSUE THREAD

**Issue by krazynez** [PSP-Archive/ARK-4#250]
[PSP Homebrew Community](https://discord.gg/bePrj9W)

Located in the **#ark-cfw channel**

**Comment by Leokinss** [comment]
Hi I can't access the discord anymore. Did it get taken down? Is there an alternative place I can ask questions?

**Comment by krazynez** [comment]
> Hi I can't access the discord anymore. Did it get taken down? Is there an alternative place I can ask questions?

Link still works fine. Unless you were banned.

**Comment by Leokinss** [comment]
My discord browser login was messed up. I can access now. Thanks
