### ISSUE TITLE
How to use pro online ?

### ISSUE THREAD

**Issue by cyberbasty** [PSP-Archive/ARK-4#251]
### New Feature

yes i know it's not a real feature request, but how to use the pro online on ark4

**Comment by krazynez** [comment]
https://github.com/PSP-Archive/ARK-4/wiki/Recommended_Plugins#pro-online

https://www.reddit.com/r/PSP/wiki/pro_online/

**Comment by JoseAaronLopezGarcia** [comment]
I also recommend installing pro online only on those games that are compatible.

Also, every guide will tell you to disable Inferno Cache when using PRO Online. This is only true for PRO, not for ARK (it was fixed).

**Comment by krazynez** [comment]
Are we good to close this?

**Comment by JoseAaronLopezGarcia** [comment]
One last thing to note: PRO Online requires the "Force Extra Memory" setting to be enabled.
