### ISSUE TITLE
Info when no sd card

### ISSUE THREAD

**Issue by Kitki30** [PSP-Archive/ARK-4#254]
### New Feature

It will show info like

No SD Card detected! Some functions in ARK Custom Firmware will be disabled
  X OK

In VSH menu style
Setting can be disabled

**Comment by krazynez** [comment]
If you have full installation this is not true though. If no memory stick is inserted it will use proshell for ArkMenu (Custom Launchet) and Recovery

**Comment by JoseAaronLopezGarcia** [comment]
It also doesn't make any sense to use VSH menu to show these type of messages since VSH Menu is installed on memory stick by default so it won't work if there isn't one unless you're using a full installation, in which case the CFW still has all its features without a memory stick.
