### ISSUE TITLE
Recovery memory stick option

### ISSUE THREAD

**Issue by Kitki30** [PSP-Archive/ARK-4#255]
### New Feature

It will be like you can create memory stick with some tools to recovery like chrono switch to install OWF and when ark will detect it it will boot to it auto on boot

**Comment by JoseAaronLopezGarcia** [comment]
Isn't that basically what `Despertar del Cementerio` does?
It's a recovery tool to unbrick consoles using Pandora batteries. It's still not yet compatible with non-Pandora models but we'll get there.

**Comment by Kitki30** [comment]
Something like that with no pandora battery

**Comment by JoseAaronLopezGarcia** [comment]
You kinda need a Pandora Battery or Baryon Sweeper to unbrick a system. If the system isn't bricked you can use the Recovery Menu.

**Comment by Kitki30** [comment]
Ok
