### ISSUE TITLE
Auto Connect To WI-FI

### ISSUE THREAD

**Issue by Kitki30** [PSP-Archive/ARK-4#256]
### New Feature

Is this possible to connect to wifi without dialog auto it would be nice function to ark

**Comment by krazynez** [comment]
We are using Sony libs/syscalls so probably not.

**Comment by JoseAaronLopezGarcia** [comment]
It is possible, but there's an issue: battery life. Having the WLAN on at all times will drain your battery VERY fast. The PSP wasn't made for this.
