### ISSUE TITLE
More language fonts

### ISSUE THREAD

**Issue by Kitki30** [PSP-Archive/ARK-4#258]
### New Feature

Can you make fonts for languages like polish so I can make Ł in translation not L

**Comment by krazynez** [comment]
https://github.com/PSP-Archive/ARK-4/blob/main/extras/menus/arkMenu/themes/translations/resources/lang_pol.json

Please do update much appreciated

**Comment by JoseAaronLopezGarcia** [comment]
I'm not sure, we're using Sony's official PGF format, and we know it's possible to convert TTF fonts to PGF fonts, but even with that we failed with the Greek language (we had to do a workaround).
I haven't tested with other languages, might be worth a try.

**Comment by Kitki30** [comment]
@krazynez im gonna fix some translation errors

**Comment by Kitki30** [comment]
> https://github.com/PSP-Archive/ARK-4/blob/main/extras/menus/arkMenu/themes/translations/resources/lang_pol.json
> 
> Please do update much appreciated 

Accept pull request please
I fixed polish language (eg. L instead of Ł that psp is not recognizing)
Notify me when there is more to translate in my language

**Comment by JoseAaronLopezGarcia** [comment]
Closing this as I think it's been solved.
