### ISSUE TITLE
ARK 4.14.5 VSH Menu not showing up on PSP GO.

### ISSUE THREAD

**Issue by McFly75** [PSP-Archive/ARK-4#26]
ARK 4.14.5 VSH Menu not showing up on PSP GO.
Ran Ark_Live/ARK-4.14.5 and now I have no VSH menu.
But ARK-4 is running.
- [X ] GO
- ARK 4.14.5

Works fine on my PSP 3000.

**Comment by JoseAaronLopezGarcia** [comment]
I'm experiencing the same issue and similar issues with 1K. I'm looking into it.

**Comment by krazynez** [comment]
very strange if I use a pre-release after 4.14.5 its working fine. But nothing has changed for vshmenu since then.

**Comment by McFly75** [comment]
Replaced FLASH0.ARK from v1649356105 (as it seemed to be the only file changed from 4.14.5 to v1649356105)
and ran ARK_live and now VSH menu is back.

**Comment by krazynez** [comment]
@McFly75 you read my mind, was just typing if you wanted to test a pre-release

**Comment by JoseAaronLopezGarcia** [comment]
https://github.com/PSP-Archive/ARK-4/releases/tag/r146

**Comment by McFly75** [comment]
FIXED (Version 4.14.6)
