### ISSUE TITLE
Any way of enable plugin PER homebrew?

### ISSUE THREAD

**Issue by pmsobrado** [PSP-Archive/ARK-4#260]
### New Feature

I know I can enable a plugin for a certain game, with its ID. I can also enable a plugin for all homebrew. But can I enable a plugin only for a specific homebrew?

Thanks!

**Comment by JoseAaronLopezGarcia** [comment]
We can't do this cause homebrew don't properly use Game ID. They all use the same ID, some of them use Game ID from real games, etc. There's no consistency in homebrew when it comes to the ID so we can't distinguish one from the other.

**Comment by JoseAaronLopezGarcia** [comment]
That might be possible yes, via path. We actually do something similar with "launcher" keyword, we test the path to see if you're running the launcher.

Let me do something real quick and you can test it for me.

**Comment by pmsobrado** [comment]
Cool :)

**Comment by JoseAaronLopezGarcia** [comment]
You can try it here: https://github.com/PSP-Archive/ARK-4/releases/tag/v1697454709

You need to specify the full path like this:

ms0:/PSP/GAME/myhomebrew/EBOOT.PBP, ms0:/seplugins/myplugin.prx, on

or "off" if you need to disable the plugin on that specific homebrew.
Note that you can't have more than one path or combine path with regular keywords.

It also works for settings:

ms0:/PSP/GAME/myhomebrew/EBOOT.PBP, highmem, on

(or off to disable a setting on specific homebrew).

This will not work for ISO though, use GameID for those.

**Comment by pmsobrado** [comment]
When you say "Note that you can't have more than one path or combine path with regular keywords", you mean:

ONE

This works:

ms0:/PSP/GAME/myhomebrew1/EBOOT.PBP, ms0:/seplugins/myplugin.prx, on
ms0:/PSP/GAME/myhomebrew2/EBOOT.PBP, ms0:/seplugins/myplugin.prx, on

And this does not:

ms0:/PSP/GAME/myhomebrew1/EBOOT.PBP, ms0:/PSP/GAME/myhomebrew2/EBOOT.PBP, ms0:/seplugins/myplugin.prx, on

Correct?

TWO

This kind of stuff won't work:

ms0:/PSP/GAME/myhomebrew*/EBOOT.PBP, ms0:/seplugins/myplugin.prx, on
ms0:/PSP/GAME/myhomebrew(1|2)/EBOOT.PBP, ms0:/seplugins/myplugin.prx, on
ms0:/PSP/GAME/myhomebrew/*/EBOOT.PBP, ms0:/seplugins/myplugin.prx, on
...

Correct?

BTW, I guess this is totally compatible with Game Categories Lite, right? I mean, because of the slightly different paths.

**Comment by JoseAaronLopezGarcia** [comment]
Yes, yes and yes.

**Comment by pmsobrado** [comment]
Great, I'll try and post back.

**Comment by pmsobrado** [comment]
It work fine! I will keep an eye for official update. BTW, how to update standalone ARK on a Vita, just run FasterARK.vpk again?

**Comment by krazynez** [comment]
> It works fine! I will keep an eye for official update. BTW, how to update standalone ARK on a Vita, just run FasterARK.vpk again?

Awesome! You update it in the Network tab.

**Comment by pmsobrado** [comment]
You're right xD I'm a bit confused because I have Adrenaline, ARK through Adrenaline and standalone ARK (I only have standalone because of the Family Guy EUR versions that lags on Adrenaline/ARK Adrenaline for some reason).

**Comment by pmsobrado** [comment]
@JoseAaronLopezGarcia Hi, is this feature available on latest Version 4.20.66 Rev 2 release? Thanks!

**Comment by pmsobrado** [comment]
@JoseAaronLopezGarcia Hi, is this feature available on latest Version 4.20.66 Rev 2 release? Thanks!

**Comment by JoseAaronLopezGarcia** [comment]
Yes, it's available in latest release.

**Comment by pmsobrado** [comment]
Great news, thanks!
