### ISSUE TITLE
Additional features for plugins and glows in the launcher

### ISSUE THREAD

**Issue by gilgilgan** [PSP-Archive/ARK-4#261]
### New Feature

When I insert a plugin from the UI, the program always asks me for one of two save locations.
I don't think most users will want to store it in a distributed fashion. I think it would be better if you could choose one of the two positions in the settings and then forget about it.
I think it would be nice to consolidate them into one arbitrary location without giving them a choice, unless there's a good reason not to.

Also, I've noticed that when I open the plugins.txt file after working on a plugin in the UI, there are a lot of empty returns with nothing in them. The empty returns seem to persist even when the plugin is inserted and then deleted. 

The glowing string effect is cool and I can't turn it off, but it's a shame that when the glow is at its brightest, it completely covers the character, making it hard to see. If you could specify a midpoint for the glow in the options instead of turning it off completely, I think you could have both readability and coolness.

**Comment by krazynez** [comment]
> ### New Feature
> 
> When I insert a plugin from the UI, the program always asks me for one of two save locations. I don't think most users will want to store it in a distributed fashion. I think it would be better if you could choose one of the two positions in the settings and then forget about it. I think it would be nice to consolidate them into one arbitrary location without giving them a choice, unless there's a good reason not to.
> 
> Also, I've noticed that when I open the plugins.txt file after working on a plugin in the UI, there are a lot of empty returns with nothing in them. The empty returns seem to persist even when the plugin is inserted and then deleted.
> 
> The glowing string effect is cool and I can't turn it off, but it's a shame that when the glow is at its brightest, it completely covers the character, making it hard to see. If you could specify a midpoint for the glow in the options instead of turning it off completely, I think you could have both readability and coolness.

1.) That is possible, I know initially thinking when I joined was probably to consolidate everything in one folder `ARK_01234` just so it could be moved around. But yeah even I just use SEPLUGINS to save my PLUGINS.TXT. The only biggy would be for Full Flash Installation it looks in ARK_01234 first then SEPLUGINS if not found. 

2.) Yeah I am going to look into that today I think I noticed it also.

3.) Good point I like that idea.

**Comment by JoseAaronLopezGarcia** [comment]
The only reason we keep the ability to have PLUGINS.TXT on ARK_01234 is for backwards compatibility with ARK-2 installations. We can get rid of that step in the plugin installer and just have it write to SEPLUGINS.


> 
> The only biggy would be for Full Flash Installation it looks in ARK_01234 first then SEPLUGINS if not found.

No this is completely unrelated and unaffected.

**Comment by krazynez** [comment]
> The glowing string effect is cool and I can't turn it off, but it's a shame that when the glow is at its brightest, it completely covers the character, making it hard to see. If you could specify a midpoint for the glow in the options instead of turning it off completely, I think you could have both readability and coolness.

https://github.com/PSP-Archive/ARK-4/releases/download/v1697633054/ARK-4-v1697633054.zip now has a scale

**Comment by JoseAaronLopezGarcia** [comment]
Is this done?

**Comment by gilgilgan** [comment]
I installed it with fasterark but don't seem to see any changes...

**Comment by krazynez** [comment]
its not in stable only pre-release

**Comment by JoseAaronLopezGarcia** [comment]
Wasn't this already released? Closing.
