### ISSUE TITLE
Fix pro online

### ISSUE THREAD

**Issue by Kitki30** [PSP-Archive/ARK-4#264]
### New Feature

Pro online isnt loading
No menu on PS/Home button just normal psp
Do you want to close the game?
Is this ark error it showed normal on first install

**Comment by JoseAaronLopezGarcia** [comment]
PRO Online works fine, how exactly did you install it?

**Comment by Kitki30** [comment]
Get it from wiki transfer over ftp move with launcher to root
Maybe launcher changed name?
Can you disable this shit that shorts names of folders/files when copying

**Comment by JoseAaronLopezGarcia** [comment]
It shouldn't short names unless they have special non-ascii characters in them, which PRO Online shouldn't have (the file is called atpro.prx).

Use this tutorial to install the plugin on specific games, only install the plugin on games known to work with PRO Online (there are compatibility lists online, search for them).
https://github.com/PSP-Archive/ARK-4/wiki/Plugins#per-game-plugin-install

**Comment by krazynez** [comment]
I have tested it with Socom FTB and it was working fine. Which game are you trying to test with?

**Comment by Kitki30** [comment]
> I have tested it with Socom FTB and it was working fine. Which game are you trying to test with?

Tekken 6
Tried both on UPnP and DNZ
Tekken is downloaded from random website

**Comment by Kitki30** [comment]
On socom and sushicat servers

**Comment by JoseAaronLopezGarcia** [comment]
Did you enable "Force Extra Memory"? It's needed for PRO Online.

**Comment by Kitki30** [comment]
Yes

**Comment by Kitki30** [comment]
Btw can you merge pull request i made satelite and that xmb file for pl translation

**Comment by Kitki30** [comment]
![IMG20231019193725.jpg](https://github.com/PSP-Archive/ARK-4/assets/84147906/f33b5560-1a79-4971-a7b7-b88392a4c48d)

![IMG20231019193709.jpg](https://github.com/PSP-Archive/ARK-4/assets/84147906/6070b2e4-3e57-4251-bc9c-00f572888b23)

![IMG20231019193702.jpg](https://github.com/PSP-Archive/ARK-4/assets/84147906/9da69011-eb4b-406d-aed0-6432ae8ea859)

**Comment by krazynez** [comment]
I would only use atpro on which ever game specified and also Force Extra Memory its also best to just say UMD/ISO. Both having it set always or for any game can cause issues.

So I tested Tekken 6 out and it connects but I get no one in the lobby, however I tested on PPSSPP and I also had the same results.

**Comment by Kitki30** [comment]
> I would only use atpro on which ever game specified and also Force Extra Memory its also best to just say UMD/ISO. Both having it set always or for any game can cause issues.
> 
> So I tested Tekken 6 out and it connects but I get no one in the lobby, however I tested on PPSSPP and I also had the same results.  

Yes no one is in lobby but you are also not shpwing on socom/sushicat list

**Comment by JoseAaronLopezGarcia** [comment]
To be fair I too am having issues with PRO Online, but I know it worked before, the only change I made is the Wifi Hotspot, so it probably doesn't like the one I'm using right now.

PRO Online is known to be very finicky and is hard to get working.

**Comment by JoseAaronLopezGarcia** [comment]
Closing as not ARK-related (PRO Online is a different, separate project).
