### ISSUE TITLE
Random homebrew

### ISSUE THREAD

**Issue by Kitki30** [PSP-Archive/ARK-4#266]
### New Feature

So if there is random ISO option maybe create random homebrew in VSH Menu?

**Comment by JoseAaronLopezGarcia** [comment]
I already explained why this feature isn't done in another Feature Request.

To sum it up: the algorithm to scan and randomly select a homebrew would be extremely slow, specially with huge lists of homebrews and even more if they are categorized.

 This feature is however implemented in the Custom Launcher, once it has loaded you can press start to boot a random game if you have set it to do so in the settings menu.

**Comment by Kitki30** [comment]
Ok
