### ISSUE TITLE
Cipl go to ofw

### ISSUE THREAD

**Issue by Kitki30** [PSP-Archive/ARK-4#270]
### New Feature

Is there any way to go to OFW in cipl like in infinity ([HOME] Button on boot)

**Comment by JoseAaronLopezGarcia** [comment]
Yes, just like Infinity, holding HOME button when turning the console on will boot OFW.

**Comment by Kitki30** [comment]
Ok good i need to chrono switch? I have infinity

**Comment by krazynez** [comment]
@Kitki30 you should join the [Discord](https://discord.gg/bePrj9W) for questions like these.

**Comment by Kitki30** [comment]
But tell Yes/No

**Comment by krazynez** [comment]
No to temp boot OFW, follow @JoseAaronLopezGarcia steps it will boot OFW until you reboot your PSP.
