### ISSUE TITLE
Optional QWERTY keyboard for Custom Launcher

### ISSUE THREAD

**Issue by JosiF69** [PSP-Archive/ARK-4#275]
### New Feature

I know it's now almost impossible to implement the firmware's native QWERTY keyboard, but what about making one from scratch? 

It would be very useful for editing and organizing plugins.txt for example, especially if the user don't have access to a computer.  Since the psp's alphanumeric keyboard is very slow.

Of course, it's something quite complex, and I don't know how viable it is, but I hope you think about it.  I apologize for any errors in my English and thank you for your attention.

**Comment by krazynez** [comment]
The builtin keyboard has QWERTY as an alternative

**Comment by JosiF69** [comment]
> The builtin keyboard has QWERTY as an alternative

Yea, but not for homebrews

**Comment by krazynez** [comment]
That would be up to the hombrew to call osk

**Comment by JoseAaronLopezGarcia** [comment]
Yeah, each homebrew is responsible for its own OSK, we can't do anything about it.
