### ISSUE TITLE
Wont save iso drivers

### ISSUE THREAD

**Issue by damo08** [PSP-Archive/ARK-4#276]
### PSP/Vita Model

PSP-2000 (Slim)

### ARK Version

Ark 4.20.66 infinity 

### Steps to reproduce

Press select
Click advanced vsh menu
Change iso driver to sony np9660
Go back
Reset vsh

### USB Charge

Disabled

### Overclock

Always

### Power Save

Disabled

### Balanced Energy Mode

Disabled

### Autoboot Launcher

Off

### Disable PSP Go Pause

Off

### Unlock Extra Memory

Homebrew

### Memory Stick Speedup

XMB

### Inferno Cache

Off

### Skip Sony Logos

Off

### Hide PIC0 and PIC1

Off

### Hide MAC Address

Off

### Hide DLC

Off

### Turn off LEDs

Disabled

### Verification of form.

- [X] I agree that I properly filled out the items listed above.

**Comment by krazynez** [comment]
https://github.com/PSP-Archive/ARK-4/issues/92#issuecomment-1450968108

**Comment by damo08** [comment]
On pro cfw it saves the change

**Comment by krazynez** [comment]
Its a reference to let the user know which driver works for which format. Hense the section to the right of the Driver name.

**Comment by damo08** [comment]
Fixed flatout game by enabling inferno cache rr
