### ISSUE TITLE
Possibility for new frimware?

### ISSUE THREAD

**Issue by tlcd96** [PSP-Archive/ARK-4#278]
### New Feature

As we all know, 6.61 is the latest firmware for the PlayStation Portable. is there any possibility for the creation of a new firmware for the PSP like the universal 6.60 and 6.61?

As users of the PSP, we should be able to get a new firmware pre-patched and with all the features we love and new features since sony killed our store and the possibility to use some features of the PSP like music, books, and other apps that still exists. We, PSP users should be able to browse the web securely and we can't do that either.

so this is my plea to the ark developers, is there any possibility to consider releasing a new firmware instead of only patches?

**Comment by wally4000** [comment]
Wat.

**Comment by JoseAaronLopezGarcia** [comment]
There's already a project that aims at reversing/recreating the entire PSP firmware from scratch, it's called uOFW (Unofficial Official Firmware). Progress is slow but steady.
Other than that we can't really write a new firmware from scratch, the amount of work would be tremendous and completely outside the scope of a Custom Firmware.
