### ISSUE TITLE
God Eater 2 (English Patched) "PlayStation Network" message on screen

### ISSUE THREAD

**Issue by Mecario** [PSP-Archive/ARK-4#296]
### PSP/Vita Model

PSP-3000 (Slim & Bright)

### ARK Version

4.20.67 r2

### Homebrew/GAME (if applicable)

NPJH-50832

### Steps to reproduce

Simply starting the game as usual 
Additional note: issue not present on PRO-C2

### USB Charge

Disabled

### Overclock

Disabled

### Power Save

Disabled

### Balanced Energy Mode

Disabled

### Autoboot Launcher

Off

### Disable PSP Go Pause

Off

### Unlock Extra Memory

Disabled

### Memory Stick Speedup

Disabled

### Inferno Cache

Off

### Skip Sony Logos

Off

### Hide PIC0 and PIC1

Off

### Hide MAC Address

Off

### Hide DLC

Off

### Turn off LEDs

Disabled

### Verification of form.

- [X] I agree that I properly filled out the items listed above.

**Comment by krazynez** [comment]
![image](https://github.com/PSP-Archive/ARK-4/assets/39999447/d68d9487-dcfd-4ccd-ba1a-8e5ce9d65bae)

Working fine on my 3K.

**Comment by JoseAaronLopezGarcia** [comment]
Perhaps it needs extra RAM enabled? Or some other setting.

**Comment by krazynez** [comment]
> Perhaps it needs extra RAM enabled? Or some other setting.

I have nothing enabled on my 3K just brought it back to 6.61 to test so fresh stable release of ARK is installed.

**Comment by JoseAaronLopezGarcia** [comment]
Could it have anything to do with the console's region?

**Comment by Mecario** [comment]
I have an european console in case that helps

**Comment by JoseAaronLopezGarcia** [comment]
What about the firmware version?

**Comment by krazynez** [comment]
![image](https://github.com/PSP-Archive/ARK-4/assets/39999447/b04ea850-92b6-4799-8ab3-83ed67b1398f)
What it translates to, did you keep your update file for the game that are required?

**Comment by Mecario** [comment]
I went back to the official european 6.61 using chronoswitch, then ran ark4 and made it permanent with infinity, so it reads as follows: 6.61 ARK-4 Infinity∞

**Comment by JoseAaronLopezGarcia** [comment]
Perhaps he needs nploader to load the update?

**Comment by Mecario** [comment]
> ![image](https://private-user-images.githubusercontent.com/39999447/302044272-b04ea850-92b6-4799-8ab3-83ed67b1398f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5NzM4NDYsIm5iZiI6MTcwNjk3MzU0NiwicGF0aCI6Ii8zOTk5OTQ0Ny8zMDIwNDQyNzItYjA0ZWE4NTAtOTJiNi00Nzk5LThhYjMtODNlZDY3YjEzOThmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDE1MTkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwYjYxYzVjOWEyMDg4ZGQwZGY0N2U1MTQyNzlmMGNjMGRkNzhjMTMyM2M3OWVkYjk5NGEyOTA0ZGMwNDQ3ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3C_vALYqcg0RUGO9FS5u5B3f0GYMfxyEjVECm_-wXRw) What it translates to, did you keep your update file for the game that are required?

I'm pretty sure I did and it works perfectly on another psp3000 I have with proc2 (same card, so I thought it had to be on ark4's side). But I'll try to set it up again just in case.
