### ISSUE TITLE
Simulation of ps1 game crashes

### ISSUE THREAD

**Issue by kingboxnt** [PSP-Archive/ARK-4#298]
### PSP/Vita Model

PSP-1000 (Fat)

### ARK Version

6.60-4.20.67 Rev 5

### Homebrew/GAME (if applicable)

PS1: SLPS03177

### Plugins ( if applicable )

CheatMaster_R21d_CN
[CMF_R21d_CN.zip](https://github.com/PSP-Archive/ARK-4/files/14106888/CMF_R21d_CN.zip)

### Steps to reproduce

Random crash when opening CMF_R21d_CN game.

### USB Charge

Disabled

### Overclock

Disabled

### Power Save

Disabled

### Balanced Energy Mode

Disabled

### Autoboot Launcher

Off

### Disable PSP Go Pause

Off

### Unlock Extra Memory

Disabled

### Memory Stick Speedup

Disabled

### Inferno Cache

Off

### Skip Sony Logos

Off

### Hide PIC0 and PIC1

Off

### Hide MAC Address

Off

### Hide DLC

Off

### Turn off LEDs

Disabled

### Verification of form.

- [X] I agree that I properly filled out the items listed above.

**Comment by JoseAaronLopezGarcia** [comment]
How is the plugin installed? Instructions online mention enabling it for game, pops and vsh (so always), but a cheat plugin on vsh doesn't make much sense to me, but who knows.
I'll give it a try and let you know.

**Comment by krazynez** [comment]
![image](https://github.com/PSP-Archive/ARK-4/assets/39999447/c07065cc-f4bd-421f-bf75-812ecef77764)
Works fine on 1K, just they're no cheats in the db for that title. Even checked the massive database for the gameid with no results. If you can verify which db you are using that has that gameid I can look further into it.

**Comment by kingboxnt** [comment]
> ![image](https://private-user-images.githubusercontent.com/39999447/301175456-c07065cc-f4bd-421f-bf75-812ecef77764.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MTI0NTEsIm5iZiI6MTcwNjcxMjE1MSwicGF0aCI6Ii8zOTk5OTQ0Ny8zMDExNzU0NTYtYzA3MDY1Y2MtZjRiZC00MjFmLWJmNzUtODEyZWNlZjc3NzY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDE0NDIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0M2YwOWM1MWJiZGViMWI4M2NmZWE5MmMwOGEzNzdjMGRlMTNmOTY2OTMzOGU1YzAzMzE2ZGRkM2YwNTI0MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FmhdJWz6OH48nYGzNcOQyuRsHTg-Z0siYCI_UAVpl-I) Works fine on 1K, just they're no cheats in the db for that title. Even checked the massive database for the gameid with no results. If you can verify which db you are using that has that gameid I can look further into it.

I'm not using any cheat codes, just the resident plugin, and it doesn't cause a problem at the beginning of the credits, but when I enter the first level of the game, and try to play it crashes randomly, nowhere in particular, same with SLPS03050.

me and pro-c are fine.

**Comment by krazynez** [comment]
![image](https://github.com/PSP-Archive/ARK-4/assets/39999447/48a7844e-1d93-4933-a8c1-c239f9072176)
Still working, though initially I had to run it first disabling the plugin (holding Start when launching) or it would kick me back to CL (Custom Launcher) but afterwards its working still.

**Comment by JoseAaronLopezGarcia** [comment]
Any idea?

**Comment by kingboxnt** [comment]
> Any idea if this is fixed?

I replaced the ips screen, psp is temporarily paralyzed, can't try until the new screen arrives in a few days.

**Comment by kingboxnt** [comment]
It's resting in peace. I give up.

**Comment by JoseAaronLopezGarcia** [comment]
> It's resting in peace. I give up.

Why, is the console broken?

**Comment by kingboxnt** [comment]
> > It's resting in peace. I give up.
> 
> Why, is the console broken?

Replacement of ips screen need to solder, actually replace the first piece of ips screen successfully, but in the wrap insulation tape wrapped the wrong conductive tape, resulting in a short, and now the second piece of ips screen connected to the blinking green light, the motherboard should be bad, laugh!
