### ISSUE TITLE
Permanent CFW for PSP E-1000 Models

### ISSUE THREAD

**Issue by mzy1996** [PSP-Archive/ARK-4#299]
### New Feature

I got ARK-4 Running on PSP E-1000 Models but I can't do the Permanent CFW on it, Infinity got an black screen then shutdown the console, cIPL Installer says Unsupported models. Please update the Permanent CFW Methods for the PSP E-1000 Models, thanks.

**Comment by krazynez** [comment]
Please follow this guide : https://github.com/PSP-Archive/ARK-4/wiki/Infinity
