### ISSUE TITLE
[Feature Request] PSP Go Features

### ISSUE THREAD

**Issue by PS3-4K-Pro** [PSP-Archive/ARK-4#30]
PSP Go Clock/Calendar and Resume game option for Non Go Models/Adrenaline

**Comment by JoseAaronLopezGarcia** [comment]
I will check it out. Do you know if other CFW or plugin has this feature?

**Comment by JoseAaronLopezGarcia** [comment]
I can confirm that ZeroVSH Patcher for 6.60 or 6.61 works fine with ARK.
As for the pause feature, there's savestate plugins that provide much better functionality.
I'll be closing this as I don't consider it's a core CFW functionality, but more in the realms of plugins.
