### ISSUE TITLE
PS Vita's ARK-4 crashes with the C1-2749-2 error after a clean ARK-4 install by FasterARK

### ISSUE THREAD

**Issue by Databoi2023** [PSP-Archive/ARK-4#307]
### PSP/Vita Model

VTE-1000 (Vita TV)

### ARK Version

Version 4.20.68 Rev 7

### Steps to reproduce

The PS Vita's ARK-4 crashes right away with the C1-2749-2 error after a clean ARK-4 install by FasterARK.

Also, ARK-X isn't installed (which I don't want, but just to let you know), only ARK-4.

### USB Charge

Disabled

### Overclock

Disabled

### Power Save

Disabled

### Balanced Energy Mode

Disabled

### Autoboot Launcher

Off

### Disable PSP Go Pause

Off

### Unlock Extra Memory

Disabled

### Memory Stick Speedup

Disabled

### Inferno Cache

Off

### Skip Sony Logos

Off

### Hide PIC0 and PIC1

Off

### Hide MAC Address

Off

### Hide DLC

Off

### Turn off LEDs

Disabled

### Verification of form.

- [X] I agree that I properly filled out the items listed above.

**Comment by krazynez** [comment]
https://gbatemp.net/data/video/418/418628-c8473cbab78af1d73226dee9d36f640f.webm

**Comment by Databoi2023** [comment]
> https://gbatemp.net/data/video/418/418628-c8473cbab78af1d73226dee9d36f640f.webm

I know. This time it was my fault.
