### ISSUE TITLE
Where is the directory for ps1 games in arc-x? I get "no game

### ISSUE THREAD

**Issue by yyoossk** [PSP-Archive/ARK-4#308]
### PSP/Vita Model

PSP-1000 (Fat)

### ARK Version

v1707621704

### Steps to reproduce

Where is the directory for ps1 games in arc-x?
I get "no game

### USB Charge

Always

### Overclock

Always

### Power Save

Disabled

### Balanced Energy Mode

Disabled

### Autoboot Launcher

Off

### Disable PSP Go Pause

Off

### Unlock Extra Memory

Disabled

### Memory Stick Speedup

Disabled

### Inferno Cache

Off

### Skip Sony Logos

Off

### Hide PIC0 and PIC1

Off

### Hide MAC Address

Off

### Hide DLC

Off

### Turn off LEDs

Disabled

### Verification of form.

- [X] I agree that I properly filled out the items listed above.

**Comment by JoseAaronLopezGarcia** [comment]
PS1 games go in `ux0:pspemu/PSP/GAME/` and they need to be in `EBOOT.PBP` format (PSN or PSX2PSP), it can't play `.cue/.bin`, for those you have to use the `PSX2PSP` app on Windows to convert them.
