### ISSUE TITLE
[feature request] ArkLauncher: Filebrowser Startup Option

### ISSUE THREAD

**Issue by svensvond** [PSP-Archive/ARK-4#31]
#### PSP Model
- [ ] 1000 (1k/Phat)
 
- [ x] 2000 (2k/Slim)

- [ ] 3000 (3k/slim & brite)

- [ ] GO

- [ ] Street (E-1000)  

#### Ark Version
4.17

Add an option to go directly to the filebrowser when Ark-Launcher loads.

Why?
If you have a large microSD Card + many ISOs on the card, categorizing in folders is a great way to handle the iso amount. Typically the large sd card takes some time to init load - and takes ages within the default CFW PSP XMB.
Ark-Launcher with the Ark Firmware fixes that, since it loads instantly and does not load - i goes - MetaData and does not try to init the 512GB MicroSD (which also takes around 25 seconds).
I have my Games categorized in folders like so: iso\action, iso\sports .. etc.
Ark-Launcher does not show the games on the mainscreen since they are in the folders, which is ok (if we could have folders here it would be great of course) - i go to the filebrowser on the top and launch the isos directly - also with almost no directory-content loading time - which works greate.
An option to go directly to the filebrowser on startup would be great!

**Comment by JoseAaronLopezGarcia** [comment]
This is a good idea, I will work it out as a setting for the custom launcher.

**Comment by JoseAaronLopezGarcia** [comment]
This feature will be available in the next update.

**Comment by JoseAaronLopezGarcia** [comment]
https://github.com/PSP-Archive/ARK-4/releases/tag/v1657825892
