### ISSUE TITLE
How to activate USB in recovery mode?

### ISSUE THREAD

**Issue by isMMa** [PSP-Archive/ARK-4#312]
### New Feature

In recovery mode down show any setting to activate conection USB

**Comment by krazynez** [comment]
Its the second option in recovery? Unless your using older Recovery mode then its in Files tab press LTrigger and enable USB mode.

**Comment by isMMa** [comment]
Thanks, I don't know why but 2 different recoveries appear

**Comment by krazynez** [comment]
> Thanks, I don't know why but 2 different recoveries appear

might be a mixture of older ARK-4 and newer ARK-4, Recovery now is the ascii version. Did you find the setting?
