### ISSUE TITLE
Missing some options in ARK-X, Vita TV

### ISSUE THREAD

**Issue by iAmGhost** [PSP-Archive/ARK-4#315]
### PSP/Vita Model

VTE-1000 (Vita TV)

### ARK Version

4.20.68 Rev 8

### Steps to reproduce

I'm not sure this is ARK-X's problem or Vita FW's, but some options in Settings of ARK-X have fewer options than Vita(PCH-2000).

Controller Settings:
![2024-02-17-212744](https://github.com/PSP-Archive/ARK-4/assets/1367707/a3f76aa0-9258-4b1f-b4fe-505e30cb3e45)
![2024-02-17-212733](https://github.com/PSP-Archive/ARK-4/assets/1367707/9115765d-6de8-453f-90a1-c3a10a9fedc3)

Other Settings:
![2024-02-17-211318](https://github.com/PSP-Archive/ARK-4/assets/1367707/78c4de2c-4581-4594-bede-8d51ccf2c050)
![2024-02-17-212121](https://github.com/PSP-Archive/ARK-4/assets/1367707/a3dd2136-7f84-4029-8605-37130cfce171)

### USB Charge

Disabled

### Overclock

Disabled

### Power Save

Disabled

### Balanced Energy Mode

Disabled

### Autoboot Launcher

Off

### Disable PSP Go Pause

Off

### Unlock Extra Memory

Disabled

### Memory Stick Speedup

Disabled

### Inferno Cache

Off

### Skip Sony Logos

Off

### Hide PIC0 and PIC1

Off

### Hide MAC Address

Off

### Hide DLC

Off

### Turn off LEDs

Disabled

### Verification of form.

- [X] I agree that I properly filled out the items listed above.

**Comment by nallwolf** [comment]
This is a normal limitation of the Vita TV. The menus are like this even in official PSN games.

1. There's no reason to assign buttons when the DS3/DS4 matches the DS1, only useful setting is to map left analog to d-pad
2. There are no touch panels to assign on the Vita TV
3. "Assign Controllers" is done on the first screen you get after holding the PS button

As for the other settings (screen size, volume, bilinear filtering), Sony restricted a lot on the Vita TV for no good reason, these are just another casualty.

**Comment by iAmGhost** [comment]
> This is a normal limitation of the Vita TV. The menus are like this even in official PSN games.

I just found that too, thanks.
I found that I can enable those options by installing PSOneScrot plugin.
Since this is unrelated with ARK-X, I'll close this issue.
