### ISSUE TITLE
Issues with cIPL

### ISSUE THREAD

**Issue by shahbazubaid** [PSP-Archive/ARK-4#320]
### PSP/Vita Model

PSP-1000 (Fat)

### ARK Version

r10

### Steps to reproduce

I've installed ARK-4 on my PSP 1000 using cIPL. But when I use a different memory card (other than the one I used to install ARK-4), the CFW seemingly disappears from the XMB. I mean, it doesn't show the extra menu options (like Custom Firmware Settings, Debug Settings etc. all which are specific to ARK-4) on the XMB. Neither can I pull up the VSH menu when pressing select on the XMB, nor can I boot into recovery when pressing R when booting up.

The System Information still shows 6.61 ARK-4 cIPL, and I'm still able to load the ISOs. When I put back the normal memory stick (which I used to install ARK-4), this issue is not seen, but when I insert a different memory stick, it arises again.

### USB Charge

Always

### Overclock

Always

### Power Save

Disabled

### Balanced Energy Mode

Disabled

### Autoboot Launcher

Off

### Disable PSP Go Pause

Off

### Unlock Extra Memory

Always

### Memory Stick Speedup

Always

### Inferno Cache

LRU

### Skip Sony Logos

Off

### Hide PIC0 and PIC1

Off

### Hide MAC Address

Off

### Hide DLC

Off

### Turn off LEDs

Disabled

### Verification of form.

- [X] I agree that I properly filled out the items listed above.

**Comment by krazynez** [comment]
Because your missing savedata. ARK-4 is still loaded however. Its recommened to do a Full Flash Install to have recovery and vshmenu.

**Comment by shahbazubaid** [comment]
Yes, you're right. It was indeed because the save file wasn't present on the 2nd memory card.
