### ISSUE TITLE
Chinese in the VSH menu does not display properly

### ISSUE THREAD

**Issue by li-fstz** [PSP-Archive/ARK-4#327]
### PSP/Vita Model

PSP-3000 (Slim & Bright)

### ARK Version

4.20.68 r12

### Steps to reproduce

1. Choose `简体中文` in `Settings - System Settings - System Language`
![pic_0002](https://github.com/PSP-Archive/ARK-4/assets/5616727/80b5487c-3a2b-42db-9792-41dcf6c33209)
2. Open VSH menu
![pic_0003](https://github.com/PSP-Archive/ARK-4/assets/5616727/bbdc5c9c-14a2-45ce-aba8-d269aea5f31c)

### USB Charge

Always

### Overclock

Always

### Power Save

Disabled

### Balanced Energy Mode

Disabled

### Autoboot Launcher

Off

### Disable PSP Go Pause

Off

### Unlock Extra Memory

Disabled

### Memory Stick Speedup

Always

### Inferno Cache

LRU

### Skip Sony Logos

Off

### Hide PIC0 and PIC1

Off

### Hide MAC Address

On

### Hide DLC

Off

### Turn off LEDs

Disabled

### Verification of form.

- [X] I agree that I properly filled out the items listed above.

**Comment by JoseAaronLopezGarcia** [comment]
As mentioned here: https://github.com/PSP-Archive/ARK-4/pull/300#issuecomment-2036973787

We need to create font files with chinese characters in the format that the font reader expects.

**Comment by li-fstz** [comment]
the code of drawing font is `extras/menus/vshmenu/blit.c`, only work for ascii (or any 8-bit encoding), 
so chinese cannot be read correctly in UTF-8 (japanese and korean also)

**Comment by krazynez** [comment]
> the code of drawing font is `extras/menus/vshmenu/blit.c`, only work for ascii (or any 8-bit encoding), so chinese cannot be read correctly in UTF-8 (japanese and korean also)

should be in advancedvshmenu vshmenu is the old menu we do not use. But avshmenu is very much based on that still so probably same issue applies. (More of and FYI)

**Comment by li-fstz** [comment]
the `pf` font only support 256 characters, it‘s unlikely to create a standard encoded chinese font

**Comment by JoseAaronLopezGarcia** [comment]
> > the code of drawing font is `extras/menus/vshmenu/blit.c`, only work for ascii (or any 8-bit encoding), so chinese cannot be read correctly in UTF-8 (japanese and korean also)
> 
> should be in advancedvsh. vshmenu is the old menu we do not use. But avshmenu is very much based on that still so probably same issue applies. (More of and FYI)

I renamed advancedvsh to vshmenu to keep it standarized with the others.

**Comment by JoseAaronLopezGarcia** [comment]
> the code of drawing font is `extras/menus/vshmenu/blit.c`, only work for ascii (or any 8-bit encoding), so chinese cannot be read correctly in UTF-8 (japanese and korean also)

We do have the source code so we might be able to add UTF-8 support to it. Either that or maybe change to the intraFont library so we can load the native PSP fonts as we do in Custom Launcher.

**Comment by li-fstz** [comment]
makeing a couple specific encoding satelite_chs.txt and pf font maybe an acceptability idea?
256 may cover all characters in the chinese vsh menu

**Comment by JoseAaronLopezGarcia** [comment]
> makeing a couple specific encoding satelite_chs.txt and pf font maybe an acceptability idea? 256 may cover all characters in the chinese vsh menu

So you mean to map ASCII characters to (common/needed) Chinese characters?
We did something similar with the Greek translation in Custom Launcher. I couldn't get intraFont to display Greek characters (even though it should be able to) but I managed to overcome this by creating a special font that mapped Latin characters to Greek.

**Comment by li-fstz** [comment]
the idea i'm talking about is more like a temporary solution, the specially satelite_chs.txt and pf-font are not convenient for updating.
the solution you're talking about is more conducive to extend to other unsupported languages.

**Comment by li-fstz** [comment]
done
i make a couple pf and txt, it's work

the pf look like:
![chs](https://github.com/PSP-Archive/ARK-4/assets/5616727/52c75504-6c36-443b-84a1-7bd9cc1d8742)

![pic_0006](https://github.com/PSP-Archive/ARK-4/assets/5616727/90442d60-84e9-4584-a828-62b03abcbaef)
![pic_0007](https://github.com/PSP-Archive/ARK-4/assets/5616727/b969d2e5-0f53-476e-b69e-04b66b60fc9a)

**Comment by JoseAaronLopezGarcia** [comment]
Nice! Open a Pull Request and we will merge it.
