### ISSUE TITLE
cIPL install?

### ISSUE THREAD

**Issue by JohnVeness** [PSP-Archive/ARK-4#34]
#### PSP Model
- [x] 1000 (1k/Phat)
 
- [x] 2000 (2k/Slim)

- [ ] 3000 (3k/slim & brite)

- [ ] GO

- [ ] Street (E-1000)  

#### Ark Version

None yet

#### Question

Hi, I have a PSP-1000 and an early model PSP-2000 (compatible with cIPL). I was wondering if it was possible to have a cIPL version of ARK for coldboot, rather than using Infinity? From what I've read, it's better to use cIPL if your PSP model is compatible (I'm not sure why - maybe faster boots, or better recoverability?). Thanks!

**Comment by JoseAaronLopezGarcia** [comment]
Yeah sure it's in the TODO list.

**Comment by JoseAaronLopezGarcia** [comment]
Already available in version 4.19 onwards.
