### ISSUE TITLE
PSPgo not possible to create a MMS with DC ARK Installer

### ISSUE THREAD

**Issue by XestoX** [PSP-Archive/ARK-4#353]
I always got the error "Error decrypting 6.61 updater."

I done it like on all my other PSP's (phat, slim brite and street) before.

I placed the ARK DC Installer on the memory stick not the internal memory and the pspgo version of the 6.61 firmware in the root of the same. do I miss something?

### PSP/Vita Model

PSP-N1000 (PSP Go)

### ARK Version

4.20.69

### Steps to reproduce

1. Start pspgo 2. launch DC ARK Installer 3. It failes decrypting FW

### USB Charge

Disabled

### Overclock

Always

### Power Save

Disabled

### Balanced Energy Mode

Disabled

### Autoboot Launcher

Off

### Disable PSP Go Pause

Off

### Unlock Extra Memory

Always

### Memory Stick Speedup

Always

### Inferno Cache

LRU

### Skip Sony Logos

Off

### Hide PIC0 and PIC1

Off

### Hide MAC Address

On

### Hide DLC

Off

### Turn off LEDs

Disabled

### Verification of form.

- [X] I agree that I properly filled out the items listed above.

**Comment by krazynez** [comment]
X000 = 661.PBP
GO    = 661GO.PBP
