### ISSUE TITLE
only loads halfway on japanese psp

### ISSUE THREAD

**Issue by MarioMasta64** [PSP-Archive/ARK-4#363]
### PSP/Vita Model

PSP-3000 (Slim & Bright)

### ARK Version

4

### Steps to reproduce

1. buy a japanese psp
2. run ark cfw
3. ark cfw loads and replaces system settings info and games in iso form show up however the select menu is non-functional (the button is fine) and extras only contains 1seg comic reader and x-radar portable

im unsure about the select issue but would the different items in extras effect showing cfw settings?

### USB Charge

Disabled

### Overclock

Disabled

### Power Save

Disabled

### Balanced Energy Mode

Disabled

### Autoboot Launcher

Off

### Disable PSP Go Pause

Off

### Unlock Extra Memory

Disabled

### Memory Stick Speedup

Disabled

### Inferno Cache

Off

### Skip Sony Logos

Off

### Hide PIC0 and PIC1

Off

### Hide MAC Address

Off

### Hide DLC

Off

### Turn off LEDs

Disabled

### Verification of form.

- [X] I agree that I properly filled out the items listed above.

**Comment by MarioMasta64** [comment]
also another note: the update option is also not replaced with ark update

**Comment by nallwolf** [comment]
I have a Japanese PSP-3000 in front of me right now with the newest version of ARK-4 Live running on a freshly installed 6.61 with no problems. Either the files on your memory stick are corrupted or you potentially have a bad shoulder button (would cause the VSH menu to not show up when pressing select, but shouldn't mess with the Extras icons). You should re-download ARK and copy the savedata to your memory stick again. If you still have the problem, try testing your buttons with Key[s]Tester: https://www.gamebrew.org/wiki/KeysTester_PSP

**Comment by MarioMasta64** [comment]
i redownloaded it several times
it works perfectly fine on pro-c but not ark-4
also according to the button tester every button works perfectly fine nothing is being held

**Comment by MarioMasta64** [comment]
![17146634809613405247899855802762](https://github.com/PSP-Archive/ARK-4/assets/20806802/3c0fd975-c2f8-4585-9c2d-de861c40fd45)
![17146634936633465963397670521455](https://github.com/PSP-Archive/ARK-4/assets/20806802/bb405181-e99e-48eb-ae52-928ce2756ae9)
![17146635106403770936334342086941](https://github.com/PSP-Archive/ARK-4/assets/20806802/4875223d-4fb4-42b1-a61c-4e3b33563dd4)
![17146635392664533359421268237571](https://github.com/PSP-Archive/ARK-4/assets/20806802/a443d233-c712-4bfb-91df-4abed18a50ec)
![17146635733816579401983018604764](https://github.com/PSP-Archive/ARK-4/assets/20806802/c38e12d2-0077-4e83-aaae-532f87c7eebd)

evidence of everything ive been talking about above

also its not the files cause the other psp i did right before it is fine
![17146636527126009679193086936085](https://github.com/PSP-Archive/ARK-4/assets/20806802/218bee9f-a73e-4af9-854c-c716ac0cb5af)
![17146636707784472103491472066400](https://github.com/PSP-Archive/ARK-4/assets/20806802/422d4b99-c3fb-4d3d-9e69-00fc4a800d64)

**Comment by MarioMasta64** [comment]
perhaps it isnt specifically that its a japanese psp but in case its relevant any
![17146638095798925558692207037329](https://github.com/PSP-Archive/ARK-4/assets/20806802/1fde8dc1-dc1a-4572-88a8-7cdf7584577f)

**Comment by MarioMasta64** [comment]
okay an update on this: for some reason the memory adapter i used was the culprit

i honestly dont know how but the comment of a corrupted memory stick helped me find this out
