### ISSUE TITLE
Latest ARK4 release crashes when loading Stage 2 on PSP 3000 6.61 OFW

### ISSUE THREAD

**Issue by MarkZ90** [PSP-Archive/ARK-4#368]
### PSP/Vita Model

PSP-3000 (Slim & Bright)

### ARK Version

v1715537822

### Steps to reproduce

1. Copy ARK_01234 folder into /PSP/SAVEDATA/ folder.
2. Copy ARK_Loader folder into /PSP/GAME/ folder.
3. Run ARK Loader
4. ARK Loader hangs at:

Stage 1 Starting
Loading Stage 2 at: ms0:/PSP/SAVEDATA/ARK_01234/ARK4.BIN
Executing ARK Stage 2

5. 4.20.69 (DC10) r4 works correctly.

### USB Charge

Disabled

### Overclock

Disabled

### Power Save

Disabled

### Balanced Energy Mode

Disabled

### Autoboot Launcher

Off

### Disable PSP Go Pause

Off

### Unlock Extra Memory

Disabled

### Memory Stick Speedup

Disabled

### Inferno Cache

Off

### Skip Sony Logos

Off

### Hide PIC0 and PIC1

Off

### Hide MAC Address

Off

### Hide DLC

Off

### Turn off LEDs

Disabled

### Verification of form.

- [X] I agree that I properly filled out the items listed above.

**Comment by MarkZ90** [comment]
It seems v1715432584 introduced the issue as the previous versions work fine.

**Comment by krazynez** [comment]
We are aware thanks.

**Comment by krazynez** [comment]
Should be fixed with latest release now.

**Comment by krazynez** [comment]
Can you verify it works in latest release.

**Comment by JoseAaronLopezGarcia** [comment]
> Can you verify it works in latest release.

Yes this was fixed.

**Comment by Varun-garg** [comment]
I got same issue in ARK-4-v1722213839-DEBUG.

**Comment by renegade2k** [comment]
Got the same bug with my PSP 3004 fw 6.60 and ARK4 r180
