### ISSUE TITLE
[Change Request] Ark Filebrowser width

### ISSUE THREAD

**Issue by svensvond** [PSP-Archive/ARK-4#37]
#### Ark Version

2022-07-15  [prerelease](https://github.com/PSP-Archive/ARK-4/releases/tag/v1657850931)

Currently there is a lot of free space on the left in the ArkFile Browser. This Space could be used to display a larger part of the filenames.

![IMG_20220715_154308](https://user-images.githubusercontent.com/37634123/179237081-d62521fd-5cd3-48fe-ab17-186c19c51f89.jpg)
)

**Comment by TheSubPlayer** [comment]
This space are reserved for menu (Press L)

**Comment by JoseAaronLopezGarcia** [comment]
Here you go: https://github.com/PSP-Archive/ARK-4/releases/tag/r181
