### ISSUE TITLE
Custom Launcher in permanent cIPL installation?

### ISSUE THREAD

**Issue by John-Dekka** [PSP-Archive/ARK-4#372]
### New Feature

Hy, is it possible to install the custom launcher in the permanent cIPL variant?

I have a slim 2004, 6.61 and installed the permanent cIPL version of the latest ARK. So, I removed the ark_12345 folder from my SD card.

**Comment by krazynez** [comment]
No CL is to big to fit in flash if that is what you are referring to. That is why we have pro shell instead being used when you do a full flash install.

**Comment by John-Dekka** [comment]
I see, thanks.
