### ISSUE TITLE
Livearea features for ARK-X?

### ISSUE THREAD

**Issue by pmsobrado** [PSP-Archive/ARK-4#377]
### PSP/Vita Model

PCH-2000 (Vita Slim)

### ARK Version

Version 4.20.69 (DC10) r8

### Steps to reproduce

I've noticed that the Livearea has some extra features for ARK-X bubbles:

![imagen](https://github.com/PSP-Archive/ARK-4/assets/17699739/a3e697a9-569e-45b4-b946-dd0d127f8d2b)
![pokesute_off](https://github.com/PSP-Archive/ARK-4/assets/17699739/bc866028-9c32-4d22-a5e5-eb15f0665bb3)
![pokesute_on](https://github.com/PSP-Archive/ARK-4/assets/17699739/dff66c34-00c0-44c6-83e3-52bfe1df4f06)
![ps1](https://github.com/PSP-Archive/ARK-4/assets/17699739/534bc05b-2adf-4305-a630-84c73bfffae3)

They seem to be related to poketstation, however I can't see them and I haven't found any info on the wiki regarding this.

Is there a way to enable them? Is this just part of a feature that is not yet complete and will be in the future?

Thanks!

### USB Charge

Disabled

### Overclock

Disabled

### Power Save

Disabled

### Balanced Energy Mode

Disabled

### Autoboot Launcher

Off

### Disable PSP Go Pause

Off

### Unlock Extra Memory

Disabled

### Memory Stick Speedup

Disabled

### Inferno Cache

Off

### Skip Sony Logos

Off

### Hide PIC0 and PIC1

Off

### Hide MAC Address

Off

### Hide DLC

Off

### Turn off LEDs

Disabled

### Verification of form.

- [X] I agree that I properly filled out the items listed above.

**Comment by krazynez** [comment]
Those are just generic icvons we don't have any functionality with them

**Comment by pmsobrado** [comment]
Got it, thanks!

**Comment by LiEnby** [comment]
these icons appear on every PS1 classic, if you *really* and are only actually enabled in a select few.

if you really want pocketstation support, you can make use of https://silica.codes/Li/PocketstationUnlocker to force unlock it on every "PS1 Classic"

**Comment by pmsobrado** [comment]
Thanks!
