### ISSUE TITLE
cIPL Wiki is unclear and misleading

### ISSUE THREAD

**Issue by kusazh** [PSP-Archive/ARK-4#378]
### New Feature

https://github.com/PSP-Archive/ARK-4/wiki/cIPL

1. The system version should be `6.61` since the new cIPL supports only `6.61`.
2. There is no proper tutorial for using cIPL on other CFW (PRO/ME).

**Comment by kusazh** [comment]
Also, I would like to translate `VSH_LANG.TXT`/`XMB_LANG.TXT` into Chinese (simplified/traditional). But I didn't find the English version of them.

**Comment by JoseAaronLopezGarcia** [comment]
1. Classic cIPL is compatible with both 6.60 and 6.61, the readme states this.
2. This isn't a PRO/ME project page.

As for translations, we don't have a plain text english version, the english text is hardcoded (https://github.com/PSP-Archive/ARK-4/blob/main/extras/menus/vshmenu/trans_en.c).
For Chinese we had a user come up with a clever solution so we can use the 8 bit ascii to display special chinese characters.
More information here: https://github.com/PSP-Archive/ARK-4/pull/329

**Comment by krazynez** [comment]
Number 1 is resolved. I agree with @JoseAaronLopezGarcia for number 2. If we add that users will come to us for ME and PRO support/request.

**Comment by kusazh** [comment]
Thank you for clarifying.
