### ISSUE TITLE
Request to add switch for ISO modes

### ISSUE THREAD

**Issue by Dark-Jaguar** [PSP-Archive/ARK-4#381]
### New Feature

As much as I've had success with the Inferno ISO driver, an option to switch to Sony's own NP9660 would be appreciated to restore what other custom firmware solutions have.  Would this be doable?

**Comment by JoseAaronLopezGarcia** [comment]
Convert the game to PBP format.

**Comment by Dark-Jaguar** [comment]
I'm not sure I understand.

**Comment by krazynez** [comment]
ISO,CSO,JSO,ZSO all use Inferno2. EBOOT.PBP's use Sony NP9660

**Comment by JoseAaronLopezGarcia** [comment]
Sony NP9660 is the Official Sony driver used for the Official Sony format. We don't use NP9660 for unofficial formats such as ISO.
The CFW will use one driver or the other depending on the format.

There's really not that many games that are better using Sony's format and driver.

**Comment by Dark-Jaguar** [comment]
Thank you I understand now.  That said, the option was nice in other custom firmwares, and would be easier than file converting a bunch of ripped iso's, especially for quickly A/B testing.

**Comment by krazynez** [comment]
> Thank you I understand now. That said, the option was nice in other custom firmwares, and would be easier than file converting a bunch of ripped iso's, especially for quickly A/B testing.

Your still not quite understanding. We don't have the other drivers at all. So if we created a option for it then it would still do nothing because the drivers would be missing.
