### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by ideafix13** [PSP-Archive/ARK-4#386]
I’m trying to transfer my psp save games states into the psp go with ark4. But when I try to load the save state it gives me an error. It says that it was created with another os. What can I do to load the game correctly?  It’s happening with Gran turismo 4. Thank you very much in advance.

**Comment by krazynez** [comment]
From a PSP to another PSP or PPSSPP to PSP? (which I think you can't do AFAIK)

**Comment by JoseAaronLopezGarcia** [comment]
ARK doesn't have any support for savestates, different plugins might have different formats and it seems there isn't a standard format.

**Comment by ideafix13** [comment]
I’m trying to import from a PSP to another PSP with ark4. But when I try to load the save game it gives me an error.

**Comment by JoseAaronLopezGarcia** [comment]
Some saves can't be transfered and you need to use a tool to convert them for the other console.

**Comment by ideafix13** [comment]
Do you know any tool? Gracias

**Comment by JoseAaronLopezGarcia** [comment]
https://github.com/bucanero/apollo-psp
