### ISSUE TITLE
Easy way to exit from Custom Launcher to the XMB/VSH

### ISSUE THREAD

**Issue by schm1dtmac** [PSP-Archive/ARK-4#388]
### New Feature

For those users who prefer using the XMB/VSH as their main interface for the PSP, like myself, but who may find it handy to use the custom launcher every now and again to do various tasks (e.g. installing plugins without editing files manually, on-device file management, etc), it would be convenient to have a way to actually get OUT of the custom launcher and back into the XMB. 

By default, the exit shortcut always exits to the custom launcher even if you didn't enable auto-booting to it in CFW settings, so that's a no-go currently. I don't see anything obvious in the UI that'd let me exit either, given HOME just hides most menu items but doesn't invoke the standard PSP HOME menu that'd let you quit an app, nor does any other button invoke any menu possibly relevant to exiting the custom launcher. It's probably an unimplemented feature then and needs adding for those who would find it useful.

**Comment by krazynez** [comment]
The shortcut is for custom launcher that is why its not an Exit shortcut. You press Triangle in Custom Launcher and all the way to the right is Exit.
