### ISSUE TITLE
ARK-4 Firmware: Incompatibility with .ctf Theme Plugins - Extras Category Misalignment and Launcher Inaccessibility

### ISSUE THREAD

**Issue by Plasmaphys** [PSP-Archive/ARK-4#392]
### PSP/Vita Model

PSP-3000 (Slim & Bright)

### ARK Version

4.20.69 r11

### Plugins ( if applicable )

ms0:/seplugins/cxmb/cxmb.prx on

### Steps to reproduce

Incompatibility with .ctf Theme Plugins:
1. Install ARK-4 firmware on your PSP.
2. Apply any .ctf theme plugin that includes modifications to the XMB (Cross Media Bar).
3. Navigate to the Extras category where the Firmware settings and launcher are located.
4. Observe the appearance and behavior of the Extras category.
5. Note any misalignment, missing elements, or inability to access the Firmware settings.

Launcher Inaccessibility:
1. Turn on your PSP with a .ctf plugin installed and on.
2. Attempt to open the launcher from the Extras category.
3. The PSP freezes up while loading the launcher, and eventually shuts down.

### USB Charge

Disabled

### Overclock

Always

### Power Save

Always

### Balanced Energy Mode

Always

### Autoboot Launcher

Off

### Disable PSP Go Pause

Off

### Unlock Extra Memory

Always

### Memory Stick Speedup

Always

### Inferno Cache

LRU

### Skip Sony Logos

Off

### Hide PIC0 and PIC1

On

### Hide MAC Address

On

### Hide DLC

On

### Turn off LEDs

Disabled

### Verification of form.

- [X] I agree that I properly filled out the items listed above.

**Comment by krazynez** [comment]
![2024-08-17-09-56-25-078](https://github.com/user-attachments/assets/f6b34edd-19e8-41fd-9e54-6c7df244c220)
Working fine. Not sure what you mean. Juat launched CL also from the xmb and worked fine.

**Comment by Plasmaphys** [comment]
Figured out what the problem was. It was the theme itself. it didn't have an extras menu. Which is where the firmware is located. I managed to fix both of my issues with a new theme aswell. I am sorry for reporting a false bug.
