### ISSUE TITLE
No work on PSVITA[SOLVED]

### ISSUE THREAD

**Issue by theheroGAC** [PSP-Archive/ARK-4#4]
tested and retested but ARK-4 does not work on psvita. No H.BIN file on vitabubble

**Comment by JoseAaronLopezGarcia** [comment]
How are you installing it?
If you are using the Bubble installed by FastARK then you need to copy VitaBubble/H.BIN into ARK_01234 (replacing).
If you are using other installations of ARK you might have to copy the K.BIN file from the previous installation.

**Comment by theheroGAC** [comment]
Hi thanks for the answer, I'm using Arkfast. In the Vitabubble folder inside ARK.zip there is no H.BIN

**Comment by JoseAaronLopezGarcia** [comment]
Correct, I must have forgotten to update release files.
You can find it here: https://github.com/PSP-Archive/ARK-4/blob/main/loader/usploit/vitabubble/H.BIN

**Comment by theheroGAC** [comment]
yes now work.Only replace H.BIN inside old a ARK_01234

**Comment by theheroGAC** [comment]
for you thank you
https://github.com/theheroGAC/ArkFast/releases/tag/2.31

**Comment by JoseAaronLopezGarcia** [comment]
Thanks, I will add a link to it on the README.

**Comment by theheroGAC** [comment]
Just for confirmation, from the old ARK-2 with this ARK-4 just replace the H.BIN file? Thanks

**Comment by JoseAaronLopezGarcia** [comment]
yes, that's where the kxploit resides in that ARK-2 release (weird that they put it there and not K.BIN).

**Comment by theheroGAC** [comment]
thank you
