### ISSUE TITLE
A paste option in the ARK menu file browser.

### ISSUE THREAD

**Issue by gtaiscool236** [PSP-Archive/ARK-4#407]
### New Feature

This section is required but the feature is pretty self-explanatory from the title so I'm not entirely sure what to put here.

**Comment by krazynez** [comment]
There is a paste option. Select a file/folder copy/cut then paste shows up.

**Comment by JoseAaronLopezGarcia** [comment]
I remember there was a feature request to have the "Paste" option hidden when nothing has been copied/cut yet. I find it funny that now we are being asked to bring it back xD
Sorry but we won't be touching that again.
