### ISSUE TITLE
When using the plugin setup with GAMEID, the custom launcher freezes and the psp switches off

### ISSUE THREAD

**Issue by Xtremegamer13579** [PSP-Archive/ARK-4#408]
### PSP/Vita Model

PSP-2000 (Slim)

### ARK Version

4.40.69 r15

### Homebrew/GAME (if applicable)

Gran Turismo

### Plugins ( if applicable )

temp AR

### Steps to reproduce

Pls try to stop the freezing and the cheatdevice for NFS Carbon OTC does not work when applying it
TempAR plugin not working on all games
I am not a person who knows about all the different codes of psp and scripting so i cannot tell you how to reproduce it

### USB Charge

Always

### Overclock

Always

### Power Save

Disabled

### Balanced Energy Mode

Disabled

### Autoboot Launcher

Off

### Disable PSP Go Pause

Off

### Unlock Extra Memory

Disabled

### Memory Stick Speedup

Always

### Inferno Cache

Off

### Skip Sony Logos

Off

### Hide PIC0 and PIC1

Off

### Hide MAC Address

On

### Hide DLC

Off

### Turn off LEDs

Disabled

### Verification of form.

- [X] I agree that I properly filled out the items listed above.

**Comment by JoseAaronLopezGarcia** [comment]
We need to see the contents of your PLUGINS.TXT file (found inside the SEPLUGIN folder).

**Comment by Xtremegamer13579** [comment]
[PLUGINS.TXT](https://github.com/user-attachments/files/17175795/PLUGINS.TXT)
Here it is

**Comment by Xtremegamer13579** [comment]
Thanks for any help with my issue

**Comment by Xtremegamer13579** [comment]
When i tried using pro c with my plugins it never work at all
I prefer ARK to Pro C ,It is much easier to use
I am also on discord so i see your messages
I will keep up with your updates
Thanks

**Comment by krazynez** [comment]
> [PLUGINS.TXT](https://github.com/user-attachments/files/17175795/PLUGINS.TXT) Here it is

always, ms0:/SEPLUGINS/category_lite.prx, on 

is incorrect. [see](https://github.com/PSP-Archive/ARK-4/wiki/Recommended-Plugins#game-categories-lite)

**Comment by Xtremegamer13579** [comment]
Category lite is working fine
It is the TempAr that isnt workong on any of my games

**Comment by krazynez** [comment]
> Category lite is working fine It is the TempAr that isnt workong on any of my games

Yes because category lite is breaking it....

**Comment by Xtremegamer13579** [comment]
So i must not connect the plugin to always
I must connect it to vsh only

**Comment by maodus** [comment]
> So i must not connect the plugin to always I must connect it to vsh only

Yep, precisely.

**Comment by Xtremegamer13579** [comment]
Trying it now

**Comment by Xtremegamer13579** [comment]
Workin
Thank you so so much🫶🏻🫶🏻🫶🏻
