### ISSUE TITLE
Enable full-size QWERTY keyboard in native OSK outside XMB/VSH for all titles

### ISSUE THREAD

**Issue by schm1dtmac** [PSP-Archive/ARK-4#409]
### New Feature

The full-size QWERTY keyboard built into the PSP's stock OSK only appears to work when the OSK is invoked within the XMB/VSH (e.g. changing nickname, using Browser, PSN stuff, etc). Invoking the system OSK within most games/apps outside the XMB however (e.g. Custom Launcher, LittleBigPlanet level rename) doesn't offer the ability to switch to the full QWERTY keyboard with the SELECT button, so you're stuck with the T9-style keyboard instead, except for some late PSP releases like MHP3rd that actually somehow do support the QWERTY layout. It would be nice, if it's even possible, to 'unlock' the full size QWERTY keyboard mode across all PSP software, new or old, using the native OSK calls unless something like memory limitations or whatever prevents it.

**Comment by JoseAaronLopezGarcia** [comment]
It's an interesting idea, not sure how possible it is but would be worth investigating.

**Comment by JoseAaronLopezGarcia** [comment]
If the plugin is only meant to run in vsh we might run into issues to run it on games/homebrew, but it's certaintly something to be checked.

**Comment by pebeto** [comment]
In games like `Monster Hunter Portable 3rd`, you can use the whole keyboard instead of the T9 style.

**Comment by JoseAaronLopezGarcia** [comment]
> I can confirm that MHP3rd does in fact support the full-size keyboard, so I wonder why other titles like LBP for PSP don't (which came out well after 5.00 did, ands require newer PSP firmware too), or why even Custom Launcher doesn't support it either. SDK related changes maybe? IDK

Maybe it's the way that the game configures the OSK.
It would be interesting to highjack sceUtilityOskInitStart and dump the config structure the game is passing down, and compare between MHP3rd and other games.

**Comment by BCDeshiG** [comment]
Just chiming in here, DBZ Tenkaichi Tag Team also supports the full size keyboard.

**Comment by JoseAaronLopezGarcia** [comment]
> > > I can confirm that MHP3rd does in fact support the full-size keyboard, so I wonder why other titles like LBP for PSP don't (which came out well after 5.00 did, ands require newer PSP firmware too), or why even Custom Launcher doesn't support it either. SDK related changes maybe? IDK
> > 
> > 
> > Maybe it's the way that the game configures the OSK. It would be interesting to highjack sceUtilityOskInitStart and dump the config structure the game is passing down, and compare between MHP3rd and other games.
> 
> I've used a custom PPSSPP build that dumps the state of the sceutilityoskinitstart params, and tried feeding all of the ones from DBZ Tenkaichi Tag Team Demo in to the Custom Launcher OSK code, but it doesn't change anything as the QWERTY layout still doesn't show up (I've also tested and confirmed that DBZ on real HW has the full-size keyboard as BCDeshiG noted even though it isn't a JP title, so it's a better test IMO than MHP3rd). Something else beyond my realm of knowledge is going on here since the OSK stuff in the open source SDKs hasn't provided much more insight afaik.

Interesting. Perhaps it's something else, something like language.
One more thing: perhaps the qwerty osk is hidden behing a compiledSdk version.
For example, playback of MP3 with frequencies other than 44000Hz is forbidden if the game/app is compiled with an old sdk version. I had to patch out that limitation for the Custom Launcher to be able to playback those types of MP3.

**Comment by JoseAaronLopezGarcia** [comment]
> You were 100% on the money @JoseAaronLopezGarcia, I modded Custom Launcher in my fork to call sceKernelSetCompiledSdkVersion passing 6.60's hex version (0x06060010) as the parameter, and that successfully unlocked the QWERTY keyboard so it is indeed a simple version check. Hopefully patching osk_plugin as a whole to bypass the check is as simple as you suggested, I'd have no clue.

Patching the osk should be the same exact patch as the mp3 library, you can add an `or` (||) and another strcmp(mod->modname, "osk_plugin"). I'm not sure if the module's name is indeed "osk_plugin" but that's easy enough to find.
