### ISSUE TITLE
Can't uninstall fatms371mod after installing via FFI app

### ISSUE THREAD

**Issue by schm1dtmac** [PSP-Archive/ARK-4#412]
### PSP/Vita Model

PSP-1000 (Fat)

### ARK Version

4.20.69 r150

### Steps to reproduce

1. Run Full Flash Installer
2. Install fatms371mod from the menu on applicable models (PSP 1K for me, in practice any model but GO)
3. Relaunch FFI after installing fatms371mod
4. Note that there's no option to uninstall fatms371mod specifically, and that the Uninstall option won't remove it either.

### USB Charge

Disabled

### Overclock

Disabled

### Power Save

Disabled

### Balanced Energy Mode

Disabled

### Autoboot Launcher

Off

### Disable PSP Go Pause

Off

### Unlock Extra Memory

Disabled

### Memory Stick Speedup

Disabled

### Inferno Cache

Off

### Skip Sony Logos

Off

### Hide PIC0 and PIC1

Off

### Hide MAC Address

Off

### Hide DLC

Off

### Turn off LEDs

Disabled

### Verification of form.

- [X] I agree that I properly filled out the items listed above.

**Comment by krazynez** [comment]
Fair point, give me a few.

**Comment by krazynez** [comment]
https://github.com/PSP-Archive/ARK-4/releases/download/v1728078267/ARK-4-v1728078267.zip
