### ISSUE TITLE
Psp slim theme default colors(2000-3000) on psp 1000 models 

### ISSUE THREAD

**Issue by zylex7** [PSP-Archive/ARK-4#415]
### New Feature

I think that's a must

**Comment by krazynez** [comment]
It already supports it you can add them or use my [slim colors](https://github.com/krazynez/slim_colors) to add them.

**Comment by JoseAaronLopezGarcia** [comment]
The feature gets enabled automatically once it detects that you've installed the slim colors file on flash.

**Comment by zylex7** [comment]
Thank you for your email I appreciate it I figured it out I have slim
colors now
