### ISSUE TITLE
[Feature Request] Custom Launcher Title Sorting Options

### ISSUE THREAD

**Issue by Dark98** [PSP-Archive/ARK-4#42]
## ARK-4 Feature Request

Sort By Name, Type/Category, etc

**Comment by JoseAaronLopezGarcia** [comment]
Custom Launcher already sorts by type/category, though to keep things simple and easy on the available screen only three categories are available (PSP Retail games, PSP Homebew and PS1 games).
Sorting by name might be a posibility, I will check it out for sure.

**Comment by JoseAaronLopezGarcia** [comment]
Done:
https://github.com/PSP-Archive/ARK-4/releases/tag/r1810
