### ISSUE TITLE
UMD Video Mounting missing in Recovery Menu

### ISSUE THREAD

**Issue by ferris1000** [PSP-Archive/ARK-4#43]
#### PSP Model
- [X] 1000 (1k/Phat)
 
- [X] 2000 (2k/Slim)

- [X] 3000 (3k/slim & brite)

- [X] GO

- [X] Street (E-1000)  

After updating my PSP 3000 from 6.61 Pro to 6.61 ARK4 I noticed that there is no way to mount UMD Video ISOs in the VSH Menu.
I tried to solve it by using an alternative VSH Menu but I couldn't get the Ultimate VSH Menu Revised to show up so I'm stuck with the ARK4 VSH Menu which is missing this feature.

It would be great if you could add this feature or at least a possibility to use an alternative VSH Menu.

**Comment by JoseAaronLopezGarcia** [comment]
To mount a Video UMD just use the file browser built into the Recovery Menu or the Custom Launcher, the ISO must be in /ISO/VIDEO/ (either ms0 or ef0 on PSPGo).
