### ISSUE TITLE
UMD Video input functionality to be like LME

### ISSUE THREAD

**Issue by SerialKillerSlash** [PSP-Archive/ARK-4#432]
### New Feature

so lme has a more stable umd video iso insert than ark-4 cuz if you put the psp to sleep then boot it up again it would say ''the disc could not be read.'' but lme makes the umd video iso stay inserted like the umd iso video wasnt removed.so i would highly recommend this upgrade for those who use that use imd videos as isos but they wanna put their psp to sleep mode then watch it again without mounting the iso to the umd drive.

**Comment by JoseAaronLopezGarcia** [comment]
I have no idea how it works on ME/LME to be honest, but I've fixed the bug and now it works exactly like a physical UMD video does.
