### ISSUE TITLE
The ability to change UMD Drivers

### ISSUE THREAD

**Issue by SerialKillerSlash** [PSP-Archive/ARK-4#433]
### New Feature

So some games work with a driver but some dont for example flatout head-on freezes the psp when the loading screen ends so please add this as a feature in the cfw settings.

**Comment by krazynez** [comment]
You can convert it to a PBP file if the ISO does not work. We only support Inferno 2 and Sony's NP9660 driver. One for ISO,ZSO,JSO,CSO, etc and Sony's for EBOOT's.

**Comment by JoseAaronLopezGarcia** [comment]
We decided to only provide support to one ISO driver for various reasons:

- Inferno is superior to other alternatives such as the M33 and ME drivers, it's easier to fix things with Inferno to make it even more superior than having to update M33/ME drivers to be on par with Inferno.
- It's better to place all efforts into one single driver than having to split that effort into multiple drivers.
- A lot of duplicated code would have to be maintained if we were to include all other ISO drivers.
- It's easier and simpler for the user as they don't have to worry about configuring anything, ISOs will work out of the box as is.
- The very few games that require NP9660 as of today are mainly games with strange anti-piracy meassures that Sony's driver circumvents but Inferno (or Stargate) has not yet, so it's a matter of research and development to get these few games to work fine with Inferno.
