### ISSUE TITLE
ARK Launcher File Browser: An 8.3-format dirname bug

### ISSUE THREAD

**Issue by Aneemasta** [PSP-Archive/ARK-4#436]
### PSP/Vita Model

PSP-3000 (Slim & Bright)

### ARK Version

FW 6.60 ARK 4.20.69r151 cIPL

### Homebrew/GAME (if applicable)

ARK Custom Launcher

### Plugins ( if applicable )

game, ms0:/SEPLUGINS/CUSHOME/cushome.prx, on
game, ms0:/SEPLUGINS/SSSSS/sssssbmp.prx, on
ULJM05472, ms0:/SEPLUGINS/DIVAPATCH/divapatch.prx, on

### Steps to reproduce

1. Download https://github.com/PSP-Archive/ARK-4/releases/download/r42069-151/ARK4.zip to your PC
2. Run ARK `Custom Launcher`
3. Enable showing file size
4. Wire your PSP to the PC
6. Enable `USB connection` from `File Browser`
7. From recently downloaded `ARK4.zip` unzip `themes/Mac OS` folder with all of its content to the root of the MemStick
8. Disable `USB connection`
9. Open `MACOS~1` folder

#### What was expected
- Names of the folders (and also files) would never change to 8.3-format (https://en.wikipedia.org/wiki/8.3_filename)
- `THEME.ARK` has non-zero size and is available to be previewed/installed

#### What was happened
- Name of the `Mac OS` folder changed to `MACOS~1`:
![20241215011639](https://github.com/user-attachments/assets/feb5e041-0fa1-4e27-ae14-7725dc42436a)
- `THEME.ARK` displayed with zero size:
![20241215011705](https://github.com/user-attachments/assets/77e6da8d-ba10-48d0-bf49-b914aa33a70d)
- When trying to preview/install `THEME.ARK` the PSP crashes
- When trying to go back from `MACOS~1` folder via `../` there is <s>unknown</s> ARK savedata folder instead of MemStick root:
![20241215011718](https://github.com/user-attachments/assets/ed1f7276-4e1a-43cd-8d92-3d7664591f41)

### USB Charge

Always

### Overclock

Disabled

### Power Save

Disabled

### Balanced Energy Mode

Disabled

### Autoboot Launcher

On

### Disable PSP Go Pause

Off

### Unlock Extra Memory

Always

### Memory Stick Speedup

Always

### Inferno Cache

LRU

### Skip Sony Logos

On

### Hide PIC0 and PIC1

On

### Hide MAC Address

On

### Hide DLC

On

### Turn off LEDs

Disabled

### Verification of form.

- [X] I agree that I properly filled out the items listed above.

**Comment by krazynez** [comment]
Indeed, so a work around is to have it compressed and extract it on the PSP. Seems to be a limitation with Sony's USB drivers we are using from what I can tell. 

I fixed the shortname issue when you copy/cut and paste within the PSP in Custom Launcher, but over USB is not the same process. Good to look into for sure though thanks.

**Comment by Aneemasta** [comment]
There was one more way to reproduce this bug: by using the https://www.gamebrew.org/wiki/Sssss_PSP plugin.
This is a pause-free screenshooter similar to wiki-recommended [PRXShot](https://github.com/PSP-Archive/ARK-4/wiki/Recommended-Plugins#prxshot-psp), but with different strategy of naming files.

Long story short, it uses an `ms0:/PICTURE/CAPTURE/` folder to save screenshots, but for the first time it creates the folder with lower-case name, which then will be displayed as 8.3-shorted by the `File Browser` until you rename it to the upper-case. Needless to say, the screenshots will have a "zero"-size too (and probably altered parent directory, but I haven't checked this back then).

**Comment by krazynez** [comment]
Looks like `pspMsPrivateDirent` might be the culprit that is the "shortname" for file browser. Let me see if I can get some more info on that.

**Comment by Aneemasta** [comment]
BTW, any chances to get rid of 8.3-shortening lowercase **<ins>file</ins>**names completely? This is still a thing with both created and copied files. Here's a case:
1. Run ARK `Custom Launcher`
2. Go to `File Browser`
3. Create a new file from the `Left Bumper` menu
4. Name it `foob.ar`
5. Repeat steps 1-4 with different name `foobarbaz.qux`
What you'll get are files named `FOOB~1.AR` and `foobarbaz.qux` respectively, which just makes no sense. With 8.3-shortening strategy currently `File Browser` makes short names longer with `~1` and keeps long names long.

**Comment by JoseAaronLopezGarcia** [comment]
fixed in latest pre-release
