### ISSUE TITLE
ARK Launcher: Add mute indicator

### ISSUE THREAD

**Issue by Aneemasta** [PSP-Archive/ARK-4#437]
### New Feature

Apart from 31 levels of audio volume (zero included), there is also a mute mode activated by `Note` long-press. Could you please add a mute indicator similar to the one from the XMB?
1. The original indicator:
![pic](https://github.com/user-attachments/assets/f3b49d05-3768-41a1-aa35-ce5a92bb40b8)
2. How it may look in the `ARK Launcher`:
![pic](https://github.com/user-attachments/assets/b6e2a073-da0c-4f7f-a8c1-d03508085b7a)
3. The original icon (extracted from screenshot): 
![mute](https://github.com/user-attachments/assets/6a96f4e9-4454-4921-aff4-8e011b8046ee)

**Comment by krazynez** [comment]
Yeah this is a good idea.

**Comment by Aneemasta** [comment]
> The only issue is ALL themes would need updates however
Probably, there could be a fallback to show nothing instead of MUTE.PNG icon when there's no one within the theme to keep compatibility with old themes.

**Comment by krazynez** [comment]
It is now in the latest pre-release. Acid knocked me against the head on that one forgot about the ya2d lib

**Comment by Aneemasta** [comment]
I see. So, you're taking a `MUSIC.PNG` from the theme with the red cross before it. Pretty good, I must say!

Thanks!
