### ISSUE TITLE
Items do not load automatically in "Game"if Files is the default menu.

### ISSUE THREAD

**Issue by svensvond** [PSP-Archive/ARK-4#44]
## ARK-4 Bugs/Issues

If file-browser is selected as default menu, click on "Game" in the nav bar results in an empty section with no items.
You need to press "select" first to get items loaded.

#### Ark Version

- 4.18.7

**Comment by JoseAaronLopezGarcia** [comment]
This is the intended behaviour, the idea of replacing the games menu with file browser is because you don't want the games menu to load automatically.
Also if games were to load automatically, it'll make the file browser very slow since the PSP is busy processing all the IO and games list.

**Comment by svensvond** [comment]
Make sense. Maybe i have a special workflow than.
Would it be possible to load the apps/games when switching to games browser?
I usually put my games in a different subfolder, so that they dont intefere with the games browser. Iam using the games browser to launch apps / differen cfw though.

**Comment by JoseAaronLopezGarcia** [comment]
Alright that's a good solution, I've updated the latest release with this fix:
https://github.com/PSP-Archive/ARK-4/releases/tag/r1810

**Comment by svensvond** [comment]
Thanks a lot!
