### ISSUE TITLE
[CL/Plugins] Reordering plugins?

### ISSUE THREAD

**Issue by Aneemasta** [PSP-Archive/ARK-4#445]
### New Feature

IDK whether the order of plugins in `PLUGINS.TXT` affects their loading sequence, but if so, it would be nice to be able to change their order in the `Plugins` menu.
As an example, I can suggest the [System Menu Mod PSP](https://www.gamebrew.org/wiki/System_Menu_Mod_PSP) plugin (for Pro CFW), where changing the order of loading plugins was done by `D-Pad` with `square` pressed.

**Comment by JoseAaronLopezGarcia** [comment]
Yes, the order of PLUGINS.TXT affects the order plugins are loaded (hence why you have to put per-game disable lines after the enable one). You can use the Custom Launcher's text editor to modify PLUGINS.TXT to your liking. You can use left/right to Copy a single line and use Square to paste it.
