### ISSUE TITLE
[XMB] Hide the Memory Stick (or System Storage) items and just display contents upfront.

### ISSUE THREAD

**Issue by schm1dtmac** [PSP-Archive/ARK-4#446]
### New Feature

May be better suited to a plugin if anything, but I haven't seen any thus yet that do what I'm requesting. That is, implementing a PS3-style approach to listing content (music, videos, games, etc) on the XMB where it's all just listed upfront instead of under the Memory Stick (or System Storage on PSPgo) submenus. Could be a neat addition that reduces clicks needed across the UI if nothing else, and for PSPgo users may be handy for combining their System Storage and Memory Stick gamelists into a single one.

**Comment by JoseAaronLopezGarcia** [comment]
Well this is better left for a plugin, but also I think it would very drastically slow down the boot process.
The custom launcher does work like this.
