### ISSUE TITLE
[DC/IDStorage regen] Regenerated IDStorage blocks PSN access

### ISSUE THREAD

**Issue by schm1dtmac** [PSP-Archive/ARK-4#447]
### PSP/Vita Model

PSP-1000 (Fat)

### ARK Version

65a6236

### Steps to reproduce

I simply installed DC-ARK to my Memory Stick, booted via new cIPL, then proceeded to regenerate IDStorage (maintaining original region and MAC address) for unrelated reasons. 
Attempting to login to PSN after this yielded an error saying access from my system is banned or temporarily suspended (irrespective of if OFW or CFW was installed to flash, heck simply putting garbage credentials triggers the error), I suspect something went awry with PSID regen stuff maybe?

### USB Charge

Disabled

### Overclock

Disabled

### Power Save

Disabled

### Balanced Energy Mode

Disabled

### Autoboot Launcher

Off

### Disable PSP Go Pause

Off

### Unlock Extra Memory

Disabled

### Memory Stick Speedup

Disabled

### Inferno Cache

Off

### Skip Sony Logos

Off

### Hide PIC0 and PIC1

Off

### Hide MAC Address

Off

### Hide DLC

Off

### Turn off LEDs

Disabled

### Verification of form.

- [X] I agree that I properly filled out the items listed above.

**Comment by krazynez** [comment]
> Closing, I read the code enough to determine that my PSID got overwritten with some other one during the regen process (in the predata stuff), so there's no chance of fixing this.

Yeah it warns you when using regen about that.
