### ISSUE TITLE
Custom Launcher Crashes

### ISSUE THREAD

**Issue by NikeDudeeGAMER** [PSP-Archive/ARK-4#448]
### PSP/Vita Model

PSP-3000 (Slim & Bright)

### ARK Version

v1735398053

### Homebrew/GAME (if applicable)

Custom Launcher

### Plugins ( if applicable )

always, ms0:/SEPLUGINS/npdrm_free.prx, on

xmb, ms0:/SEPLUGINS/dayviewer.prx, on

xmb, ms0:/SEPLUGINS/category_lite.prx, on

### Steps to reproduce

when i turn on the custom launcher the psp hd light blinks a few times then it turns off the psp

### USB Charge

Always

### Overclock

Always

### Power Save

Disabled

### Balanced Energy Mode

Disabled

### Autoboot Launcher

Off

### Disable PSP Go Pause

Off

### Unlock Extra Memory

Always

### Memory Stick Speedup

Always

### Inferno Cache

LRU

### Skip Sony Logos

Off

### Hide PIC0 and PIC1

Off

### Hide MAC Address

Off

### Hide DLC

Off

### Turn off LEDs

Disabled

### Verification of form.

- [X] I agree that I properly filled out the items listed above.

**Comment by krazynez** [comment]
Gonna need a bit more here. Can't reproduce this.

**Comment by NikeDudeeGAMER** [comment]
> Gonna need a bit more here. Can't reproduce this.

what more do i give you

**Comment by krazynez** [comment]
> > Gonna need a bit more here. Can't reproduce this.
> 
> what more do i give you

Do you have any games with corruoted icons? That has been an issue in the past.

**Comment by krazynez** [comment]
Recopying ARK_01234 fixed ( solved in discord )
