### ISSUE TITLE
[Feature request] Add video player module in psVita 

### ISSUE THREAD

**Issue by Bunkai9448** [PSP-Archive/ARK-4#449]
### New Feature

I was trying to play the same video in the vita's psp emu (both ark-4 and adrenaline). And played the same one in a PSP 3k through ark-4.

This was the encode used for the video:
```
:: Full ffmpeg commands for videos to watch in PSP
:: psVita PATH: pspemu/VIDEO/ (currently this crash the emu)
ffmpeg -i input.mp4 -flags +bitexact -vcodec libx264 -profile:v baseline -level 3.0 -s 480x272 -r 29.97 -b:v 384k -acodec aac -b:a 96k -ar 48000 -f psp -strict -2 outputPSPformatted.MP4
```

The video works in PSP but produces a crash error c-180... in psvita. Is it possible to patch the module for the emu to reproduce the video?

Thanks.

**Comment by JoseAaronLopezGarcia** [comment]
The Vita has its own video player, and the Vita's hardware is certaintly more powerful than the PSP, so its video player will also be more compatible (i.e. higher resolution, better codecs, etc).
I'm sorry but this feature makes no sense to us.
