### ISSUE TITLE
[Bug] Ark-Settings: Version string wrong

### ISSUE THREAD

**Issue by svensvond** [PSP-Archive/ARK-4#45]
#### Behavior
Version is 4.17 in ark settings

#### Expected
Version is 4.18.x in ark settings

#### Ark Version
4.18.11 + <

**Comment by JoseAaronLopezGarcia** [comment]
Not sure how to reproduce this issue, it shows correctly here.

**Comment by svensvond** [comment]
My fault.
I thought updating ARK would be enough to simply overwrite ARK_01234 in SaveData and Ark_Live in GAME.
Ark_Life lauching is required to get some data "flashed".
