### ISSUE TITLE
[Bug] "Skip Sony Logos" results in Launcher autorun not working

### ISSUE THREAD

**Issue by svensvond** [PSP-Archive/ARK-4#47]
## ARK-4 Bugs/Issues
When selecting "Skip Sony logos in XMB", "Autoboot launcher" is not working anymore.

#### Ark Version
4.18.12

#### Reproduction
- Start Recovery Menu
- Enable (always) Select Autoboot Launcher 
- Enable (always) Skip Sony logos in XMB

**Comment by JoseAaronLopezGarcia** [comment]
Fixed: https://github.com/PSP-Archive/ARK-4/releases/tag/r1813
