### ISSUE TITLE
Exception Caught/Blue screen

### ISSUE THREAD

**Issue by lightblair** [PSP-Archive/ARK-4#5]
since installing ark-4 over pro (6.60) i cant open any kind of application, including umds and homebrew, still not working after resetting to default settings and since i cant open anything i cant go back to pro. any way i could fix? and is this a known issue?

**Comment by JoseAaronLopezGarcia** [comment]
Hi, try disabling settings and plug-ins. Some settings are causing issues in the new build with PRO support. If possible, delete the PSPCOMPAT.PRX file from the ARK savedata folder until a fixed one is done.

**Comment by lightblair** [comment]
managed to fix, solution is [here](https://github.com/PSP-Archive/ARK-4/issues/9#issuecomment-862567415) for anyone who needs it
