### ISSUE TITLE
CWCheat doesnt work - gameid is wrongly detected

### ISSUE THREAD

**Issue by a0a0max** [PSP-Archive/ARK-4#52]
#### PSP Model

- [ ] PSP-E1000 (Street)
Not tested on other systems

#### Ark Version

72760699c159320e64260e7b58e77da3fb7ca213

#### Homebrew/GAME (if applicable)
Tested several psp games (e.g. Tekken, Burnout, etc.)

#### Plugins ( if applicable )
CWCheat

#### Steps to Reproduce
1. Start a game
2. Keep Select pressed to show CWCheat
3. CWCheat is shown
4. Game id detected by CWCheat seems wrong (probably associated to CWCheat itself instead of psp game)
5. No cheat can be selected

All recovery options are disabled

**Comment by a0a0max** [comment]
It was cwcheat 2.3, the latest version. Unfortunately I have no opportunity to perform tests in these weeks

**Comment by JoseAaronLopezGarcia** [comment]
Has this been solved?
