### ISSUE TITLE
[proposal] Hide ftp options on PSP street (no wifi)

### ISSUE THREAD

**Issue by a0a0max** [PSP-Archive/ARK-4#53]
As the PSP Street has no Wifi, is FTP ark capability still useful?

**Comment by JoseAaronLopezGarcia** [comment]
Yeah I understand this, but it doesn't break either way. If I were to do this, I would also have to hide "Go to ef0" on anything that isn't a PSP Go.
It's not totally a bad idea, but it's not a game breaker either. I will most likely end up doing it eventually.
