### ISSUE TITLE
C1-2858-3 error when running ARK on the PS Vita and PS TV

### ISSUE THREAD

**Issue by Windows10User2** [PSP-Archive/ARK-4#55]
I installed ARK in the PS Vita and it's crashing often when loading games with the C1-2858-3 error.

Also, I can't install ARK the right way in the PS TV since it always crashes with the C1-2858-3 error after replacing the ARK_01234 folders. It works if I don't do the latter but it looks like I stay with an old and buggy ARK version. I say buggy because it's crashing with the C1-2858-3 error when loading games too.

EDIT: I rebuilt the database in the PS Vita via Recovery Menu and apparently I no longer have this issue in it. 

In the PS TV, I replaced the ARK_01234 folders, rebuilt the database via the Recovery Menu (I had to be fast since I store my PSP games in an USB Flash Drive and one has to take it  to connect the controller's USB cable to the sole PS TV's USB port be able to access the Recovery Menu by pressing the PS button after clicking the PS Tv's power button for some seconds, choose the "Rebuild Database" setting and quickly take the USB cable from the PS TV's USB port and connect the USB Flash Drive to it) and apparently I stopped having both problems I was having.

**Comment by Windows10User2** [comment]
After all, I still have this issue.

**Comment by JoseAaronLopezGarcia** [comment]
Read the installation instructions again. You have to copy the K.BIN file from VitaBubble folder into ARK_01234 folder.
