### ISSUE TITLE
Freeze and crash without savedata

### ISSUE THREAD

**Issue by Yoti** [PSP-Archive/ARK-4#6]
1) Run "ARK Loader" without copying savedata
2) Get a crash after freeze on "Executing ARK Stage 2"

Just add a check for savedata files.

**Comment by JoseAaronLopezGarcia** [comment]
The loader needs to read files from the savedata to execute the CFW.
The best I could do is add a check to prompt the user to install the savedata folder.
This is for live CFW that is, permanent shouldn't have an issue to run even without a memory stick.

**Comment by Yoti** [comment]
No need to prompt a user, just check if file exist or not before opening.
