### ISSUE TITLE
PSP 1003 - 4.19, CIPL - Custom Launcher Recovery Mode Option Freezes

### ISSUE THREAD

**Issue by Dark98** [PSP-Archive/ARK-4#61]
Trying to launch the Recovery menu through the Custom Launcher results in freezing at the attached screenshot, works fine when running through the XMB VSH menu

![PXL_20221219_124513010](https://user-images.githubusercontent.com/5911848/208429663-9ba80bf4-59c0-4130-9db2-5535be05d7a6.jpg)

**Comment by JoseAaronLopezGarcia** [comment]
Is this still an issue in latest version (4.19.1)?

**Comment by Dark98** [comment]
Yeah, still effects 4.19.1

I've only tested a cIPL Environment if that makes any difference

**Comment by Demonic098** [comment]
I cannot reproduce that behavior
For me it's forking just fine
PSP1K TA-081 FW 661 ARK-4.19.1 cIPL.
@Dark98 Can you send more details plz.

**Comment by JoseAaronLopezGarcia** [comment]
I can't seem to reproduce the issue either. Are there any particular steps?

**Comment by Dark98** [comment]
I used chronoswitch to reflash a stock 6.60 firmware then ran ark & used the cIPL flasher..
No necessary steps, just happens when trying to launch recovery through the Custom launcher

**Comment by Demonic098** [comment]
@Dark98 have you tried latest release ?

**Comment by Dark98** [comment]
> @Dark98 have you tried latest release ?

same issue, just tested.. it worked on a previous version(i cant remember which)

**Comment by JoseAaronLopezGarcia** [comment]
Is this still a thing? I can't recall if we've been able to reproduce it.

**Comment by krazynez** [comment]
I can not reproduce this either. I just flashed 6.60 again on my Phat and then ran ARK 4.19.11 then cIPL Flasher, went into Custom Launcher and ran Recovery with no issues.

**Comment by Dark98** [comment]
@JoseAaronLopezGarcia @krazynez Unsure what changed but I just tested with the latest build(Hadn't tested since my last comment) & It's working Normally! :)
