### ISSUE TITLE
PSP 3000 freezes after exiting PSP ISOs using the PS button after having set the "Force Extra Memory" and "Inferno Cache" settings to "Always"

### ISSUE THREAD

**Issue by GitHubCFW** [PSP-Archive/ARK-4#78]
My PSP 3000 freezes after exiting PSP ISOs using the PS button after having set the "Force Extra Memory" and "Inferno Cache" settings to "Always".

**Comment by JoseAaronLopezGarcia** [comment]
It is obvious you're a dup account of windows10user. As long as nobody else can confirm this, I'm closing it.
