### ISSUE TITLE
Black screen right after running PSP games on the PS Vita and PS TV if the "Extra Memory" setting is enabled.

### ISSUE THREAD

**Issue by GitHubCFW** [PSP-Archive/ARK-4#79]
I have a black screen right after running PSP games on the PS Vita and PS TV if the "Extra Memory" setting is enabled.

**Comment by JoseAaronLopezGarcia** [comment]
Do you know how to read? This is well known.
https://github.com/PSP-Archive/ARK-4/issues/49

**Comment by GitHubCFW** [comment]
> Do you know how to read? This is well known. #49

And did you read what I said about the other issues? Why should I pay for what the other user said?
