### ISSUE TITLE
ARK crashes often in the PS Vita/PS TV's boot and often when running PSP games when it doesn't have the former issue

### ISSUE THREAD

**Issue by GitHubCFW** [PSP-Archive/ARK-4#80]
After running ARK, it often crashes in the PS Vita/PS TV's boot and often when running PSP games when it doesn't have the former issue.

Regarding the former problem, it states it will close in 10 seconds and if I don't manually close it, ARK crashes again with the C1-2858-3 error.

Regarding the latter problem, when I'm able to boot ARK in the PS Vita/PS TV, it often crashes with the C1-2858-3 error when running PSP games.

I'm on HENkaku 3.60.

![213938668-43fff44e-815e-4ffd-9408-3a35733d7ea3](https://user-images.githubusercontent.com/123328343/218313950-34750459-3b9f-414f-9d7f-946fc832423d.jpg)

![213938673-ff1b23ab-0d1b-4fea-959e-ce7b07387f8e](https://user-images.githubusercontent.com/123328343/218313959-83322c18-90ba-4d8d-a0c7-1616b8571cc8.jpg)

**Comment by JoseAaronLopezGarcia** [comment]
Closed for being spam. Also known issue with known fix.

**Comment by Darthagnon** [comment]
> Closed for being spam. Also known issue with known fix.

Googling around, and came across this issue. I've had the same one, any chance you could link me to the fix?

**Comment by JoseAaronLopezGarcia** [comment]
> > Closed for being spam. Also known issue with known fix.
> 
> Googling around, and came across this issue. I've had the same one, any chance you could link me to the fix?

It's in the readme, a simple reboot of the console fixes the issue.
