### ISSUE TITLE
[Feature Request] Option to change VSH menu background color

### ISSUE THREAD

**Issue by TheSubPlayer** [PSP-Archive/ARK-4#86]
In ME, it is possible to choose between some predefined colors, would be an interesting addition to ARK.

![image](https://user-images.githubusercontent.com/110436924/219899314-c040a000-3ead-42d6-91d1-a1a639ae11c8.png)

**Comment by krazynez** [comment]
We (@JoseAaronLopezGarcia and I) have spoke about this issue when we released it. We decided collectively to not do this (yet) as we want to focus on more on functionality over looks and feels. But I would like to keep this open to add in the future as a TODO

**Comment by JoseAaronLopezGarcia** [comment]
You can now do that with Advanced VSH Menu:
https://github.com/PSP-Archive/ARK-4/releases/tag/r41914
