### ISSUE TITLE
Crash when returning from sleep mode in Peggle & Resistance Retribution 

### ISSUE THREAD

**Issue by TheSubPlayer** [PSP-Archive/ARK-4#89]
#### PSP Model

- [X] PSP-3000 (Slim & Bright)

#### Ark Version

- 4.19.15 (also tested on 4.19.13)

#### Homebrew/GAME (if applicable)

- Peggle [NPUG-30040]
- Resistance Retribution [UCUS-98668]

#### Plugins ( if applicable )

**No plugin activated in game**

#### Steps to Reproduce
1. Launch Game
2. In menu or in game, put the PSP in sleep mode
3. The game will crash immediately or after a few seconds

#### Recovery settings

The error will continue no matter what settings are active

P.S. The game is in ISO format

**Comment by JoseAaronLopezGarcia** [comment]
Which was the last version of ARK where it was working fine? If there's any.

**Comment by JoseAaronLopezGarcia** [comment]
Fixed: https://github.com/PSP-Archive/ARK-4/releases/tag/r41918
